### ISSUE TITLE
gtest/gtest.h file not found fatal error during macOS installation

### ISSUE THREAD

**Issue by ghost** [google/s2geometry#100]
When installing the library on macOS (https://s2geometry.io/about/platforms#install), after successfully compiling S2 for the first time using cmake, the instruction is to make the S2 binary using make, which produces the following error:

```
Macbook-G:build bsod88$ make
Scanning dependencies of target gtest
[  0%] Building CXX object build_gtest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  0%] Linking CXX shared library ../../lib/libgtest.dylib
[  0%] Built target gtest
Scanning dependencies of target s2testing
[  0%] Building CXX object CMakeFiles/s2testing.dir/src/s2/s2builderutil_testing.cc.o
[  0%] Building CXX object CMakeFiles/s2testing.dir/src/s2/s2shapeutil_testing.cc.o
/Users/bsod88/Desktop/SomeProject/s2geometry/src/s2/s2shapeutil_testing.cc:20:10: fatal error: 'gtest/gtest.h' file not
      found
#include <gtest/gtest.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/s2testing.dir/src/s2/s2shapeutil_testing.cc.o] Error 1
make[1]: *** [CMakeFiles/s2testing.dir/all] Error 2
make: *** [all] Error 2
```

macOS & terminal ver 10.15.2
cmake ver 3.16.4
googletest ver 1.8.0 (same error using latest 1.10.x build)
s2geometry ver latest as of 2020-02-26

**Comment by DinosL** [comment]
I had a similar problem and my solution was to slightly change the cmake command. The new command is `cmake -D CMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/9.2.0_1/bin/g++-9 -DGTEST_ROOT=//Users/MyUser/Downloads/googletest-release-1.8.0/googletest .. `.
Change DGTEST_ROOT path with your path and you should be ok.

**Comment by rcoup** [comment]
See also #78

**Comment by micolous** [comment]
You probably _actually_ want https://github.com/google/s2geometry/issues/98#issuecomment-695161282, unfortunately the instructions on s2geometry.io are wrong.
