### ISSUE TITLE
S2Loop and S2Builder for mbr intersection

### ISSUE THREAD

**Issue by DinosL** [google/s2geometry#104]
I am trying to write a function to check if two MBRs intersect. My first thought was to create two S2Polygons and use the intersectsmethod. In order to do that I have to create S2Loops from the points of each MBR with something like this:

```
    vector<S2Point> points1;

    points1.push_back(S2Point(s.xLow, s.yLow,0));
    points1.push_back(S2Point(s.xHigh, s.yLow,0));
    points1.push_back(S2Point(s.xHigh, s.yHigh,0));
    points1.push_back(S2Point(s.xLow, s.yHigh,0));
    S2Polygon a(make_unique<S2Loop>(points1));
```

I do not use `.Normalize()` as my points are already normalized. I get the following error `ERROR Edge 1 crosses edge 3`. I believe that this is caused because S2Loop creates the full loop and connects every point with every other. 

Question 1: Is it possible to connect only the 4 points I give in that order?

Following the recommendations given at the S2Loop manual, I then tried S2Builder.  I had the same error as before when I was using S2Loop. I somehow managed to bypass it using S2Polyline and here comes 

Question 2: How can I use S2Builder to check for intersection?

I found no documentation regarding S2Builder, even though it is recommended for unsorted collection of edges. As a result, all my efforts are based on reading tests from the source code and trying to adapt the methods to my problem.

**Comment by jmr** [comment]
> `points1.push_back(S2Point(s.xLow, s.yLow,0));`
> `points1.push_back(S2Point(s.xHigh, s.yLow,0));`
> `points1.push_back(S2Point(s.xHigh, s.yHigh,0));`
> `points1.push_back(S2Point(s.xLow, s.yHigh,0));`

Are `{x,y}{Low,High}` latitudes and longitudes?

**Comment by DinosL** [comment]
No, they are actual points. Normalized to [0,1] range.

**Comment by jmr** [comment]
The z-coordinate is always zero in your example. This means the points are all on the equator. 

Can you make a self-contained example? What are the actual values of `{x,y}.{Low,High}`?

**Comment by DinosL** [comment]
My point are 2D. That is why they have a z-coordinate of 0. An example is xLow = 0.1 yLow = 0.3 xHigh = 0.6 yHigh = 0.7 .

**Comment by jmr** [comment]
This is a spherical geometry package, so I don't think it fits your use case. Lines are geodesics. Points are on the unit sphere and normalized means `x² + y² + z² ≈ 1`.

That said, if you want still want to use it, `S2LatLngRect` is for bounding boxes, and is 2-D so will work for your example.

You could use `S2LatLng::FromDegrees(0.1, 0.3).ToPoint()` etc if you really want to still use this even though your data is 2-D.

**Comment by DinosL** [comment]
Let's suppose that I have the actual coordinates(lat ,long) of the mbr and I want to test if it intersects with a poylgon that is not necessarily a rectangle. How can I do this since I cannot use intersects between a S2LatLngRect and a polygon?

**Comment by jmr** [comment]
I think your original example will work if you put the points in the z=1 plane instead of z=0 (and call `Normalize()` if the function requires normalized points). Transform any points you get back `(x, y, z) -> (x/z, y/z, 1)`. I don't really recommend this approach.

If your polygon doesn't have any holes, it should be relatively simple to check for intersection with an axis-aligned rectangle.

**Comment by DinosL** [comment]
My polygons do not have any holes and are axis-aligned, but I always get an error when I am trying to create a polygon from loops. Usually that an edge crosses another. The code is this

```
vector<S2Point> points;
for(auto i = geometry.begin(); i != geometry.end(); i++)
    points.push_back(S2LatLng::FromDegress(i->x,i->y).ToPoint());

S2Polygon a(make_unique<S2Loop>(points));


```

An example polygon. : `-87.8669 32.8253,-87.863 32.8157,-87.8633 32.8157,-87.8671 32.8252,-87.8669 32.8253`

**Comment by jmr** [comment]
It looks like you repeated the first and last point. This is already implicit in [`S2Loop`](https://github.com/google/s2geometry/blob/master/src/s2/s2loop.h#L57), so don't do that. I need a self-contained example to provide more help.

If all the edges of your polygons are axis-aligned then it's a simple for loop over the edges to check containment in a rectangle.

**Comment by DinosL** [comment]
I think I got it. At least for now :)
Thank you for your help

**Comment by DinosL** [comment]
Hello again.

I managed to make it work on small datasets with the following code.

```
    vector<S2Point> window;
    for(auto i = s.geometry->begin(); i != s.geometry->end()-1; i++)
    {
        window.push_back(S2LatLng::FromDegrees(i->y,i->x).Normalized().ToPoint());
    }
    S2Polygon a(make_unique<S2Loop>(window));

    vector<S2Point> obj;
    for(auto i = polygon->geometry->begin(); i != polygon->geometry->end()-1; i++)
    {
        obj.push_back(S2LatLng::FromDegrees(i->x,i->y).Normalized().ToPoint());
    }
    S2Polygon b(make_unique<S2Loop>(obj));

    if(a.Intersects(&b))
        return 1;
```

However, when I am using bigger datasets with more complex polygons I get the following error `ERROR Edge 95 is degenerate (duplicate vertex)`. I visualised the polygon using qgis and it has not any holes. Is there a way to print all edges? What is the way that s2 creates the edges? I mean does it connect a point to the next point I give or something else?
