### ISSUE TITLE
RegionCoverer on polygons in Py

### ISSUE THREAD

**Issue by kuanb** [google/s2geometry#105]
In the docs published here: https://s2sphere.readthedocs.io/en/latest/quickstart.html#examples
There's an example in which 2 points are used to create a rectangle and RegionCoverer is used on that to generate the `cellIds` that make up that area.

I'd like to do the same, but with a polygon. I've not seen anything in the Py docs that demonstrate how one might go about this, but in the source code I do so an `S2Polygon` class. I'm wondering if this is supported in Py and, if someone has figured out how to get a representative set of `cellIds` for a polygon with the Py bindings for `s2`; I'd very much appreciate if you'd be able to share.

Thanks!

(If there's a better place for this ques to go, please lmk and apologies for polluting the issues for the repo.)

**Comment by jmr** [comment]
Answered in https://groups.google.com/forum/#!topic/s2geometry-io/IHQXBS42lwY
