### ISSUE TITLE
S2CellId::levelpos() method

### ISSUE THREAD

**Issue by r-barnes** [google/s2geometry#113]
The `S2CellId::pos()` method returns a cell id as number 0..2^61 of all the level-30 cells on a face of the cube.

Sometimes, though, we would like to know the cell id as a number for a different level of the curve. 

For instance, the level 14 curve on a face has cells 0..2^28.

The `S2CellId::levelpos()` method I propose in PR #112 provides this functionality.

**Comment by jmr** [comment]
As discussed in #112 , this is the same as `S2CellId::distance_from_begin`, so that function's documentation will be clarified instead.

**Comment by r-barnes** [comment]
Sounds good, thank you.

**Comment by jmr** [comment]
The new documentation will be in the next release.
