### ISSUE TITLE
Question: Adding additional attribute to s2loop class for custom feature?

### ISSUE THREAD

**Issue by animesh-sharama** [google/s2geometry#116]
Hi,
I would like to add additional attribute to the s2loop class since its final I can't extend it.
The only way I can think of it is by replicating the class and adding additional constructor.

Is there any better way of doing it or the recommendation is to extend the S2Region class for such use case?

**Comment by jmr** [comment]
What are you trying to do and what do you want to add?

**Comment by animesh-sharama** [comment]
For example I want to represent a Point and Polygon for that I can use S2Point and S2Polygon, I want to have additional attribute in both S2Point and S2Polygon lets say **name** what is the recommended way to doing this?

**Comment by jmr** [comment]
How are you using your points and polygons?

The simplest way would be
```
struct NamedPolygon {
    S2Polygon polygon;
    std::string name;
}
```

If you're putting them in an `S2PointIndex`, for example, look at the `Data` template param.
https://github.com/google/s2geometry/blob/master/src/s2/s2point_index.h#L88

**Comment by animesh-sharama** [comment]
I would like to Index polygons and points and retrieve them latter.
I am clear for ```S2PointIndex``` as it accepts a custom Data while indexing.
But for Polygon I am still unclear, the ```S2ShapeIndex``` accepts Shape type, the S2Polygon is a final class and cannot be extended - https://github.com/cpovirk/s2-geometry-library-java/blob/moesync/src/com/google/common/geometry/S2Polygon.java
so the way that I thought of was to implements S2Shape and have method similar to S2Polygon and add my feature specific details as data member for example name but seems code duplication.
I am looking for a better way of doing the same.

**Comment by jmr** [comment]
Does the `MyPolyline` example in `s2shape.h` help?

https://github.com/google/s2geometry/blob/a883d90ae4d902d9a200912fcd9dcfdc2e8a1031/src/s2/s2shape.h#L240

**Comment by animesh-sharama** [comment]
No, In java it would not be possible to extend S2Polygon since its a final class.

**Comment by jmr** [comment]
If this is a Java question, try asking https://github.com/google/s2-geometry-library-java/issues.
