### ISSUE TITLE
python binding: comparison of S2Loops always wrong

### ISSUE THREAD

**Issue by calestyo** [google/s2geometry#118]
Hi.

It seems comparing two `S2Loops` gives always `false`, e.g.:
```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pywraps2 import S2CellId, S2Loop
>>> l1=S2Loop()
>>> l2=S2Loop()
>>> l1==l2
False
>>> s1=set([l1, l2])
>>> len(s1)
2
```
The same for non-empty loops.

OTOH, comparing e.g. S2CellId seems to work just as expected:
```
>>> c1= S2CellId.FromToken( "479ddfcbcc", len("479ddfcbcc") )
>>> c2= S2CellId.FromToken( "479ddfcbcc", len("479ddfcbcc") )
>>> c1==c2
True
>>> s2=set([c1,c2])
>>> len(s2)
1
```

Is this a bug or for some reason expected?

Cheers,
Chris

**Comment by jmr** [comment]
It's a bug. Try `l1.Equals(l2)`. I think adding `operator==` for `S2Loop` in C++ would fix it, but we need to think if we want to do that or just make swig call `Equals` in `__eq__`
