### ISSUE TITLE
python binding: rename it to something more obvious like s2geometry

### ISSUE THREAD

**Issue by calestyo** [google/s2geometry#122]
Hey.

Right now one has to import pywraps2, I think it would be nice if a more obvious or "native" name like s2geometry would be used.

In pull request #94 this would already be done, AFAIU.

Cheers,
Chris.

**Comment by jmr** [comment]
Just `import pywraps2 as s2`. I'll probably use the `s2` name for a new `pybind11` python interface.

**Comment by calestyo** [comment]
Well it's clear that you can "rename" it like this... but still a bit ugly, isn't it? :-D

**Comment by jmr** [comment]
It's ugly because the interface is ugly and non-Pythonic. There will be a better `pybind11` interface that can be called `s2.`

**Comment by figroc** [comment]
@jmr I've uploaded the wheels named `s2geometry` to pypi. I can transfer it to you in anytime.
