### ISSUE TITLE
Warnings with GCC 5.4

### ISSUE THREAD

**Issue by graetzer** [google/s2geometry#13]
I noticed quite a lot of warnings in clang due to signed / unsigned integer comparison as well as structs that were  forward declared as classes.

Would it be ok to submit a pull request which silences some of these ?

**Comment by jmr** [comment]
That's fine, but you'll have to [sign a CLA](https://github.com/google/s2geometry/blob/master/CONTRIBUTING.md). It's probably easier if I just fix them.

**Comment by jmr** [comment]
It looks easier to sign the CLA than I thought. 

Do you want to send me a PR with some example fixes, then do everything when those look ok?

**Comment by graetzer** [comment]
Yes, my collegue @danielhlarkin already submitted some of our patches, I will send some more when I get the time
