### ISSUE TITLE
how does uber uses s2 to divide map into cells ?

### ISSUE THREAD

**Issue by nani-samireddy** [google/s2geometry#139]

**Comment by jmr** [comment]
You'd have to ask Uber how Uber works.

You can read about the S2 cell hierarchy here: http://s2geometry.io/devguide/s2cell_hierarchy

**Comment by nani-samireddy** [comment]
bro can you please tell me where can I learn google s2 geometry. Because I am doing a project like uber for my locality. i want to use this library In the project so could you please tell me how could i learn it.

**Comment by jmr** [comment]
Take a look at http://s2geometry.io/, then look at [the examples](https://github.com/google/s2geometry/tree/master/doc/examples) and read, or at least scan, all the the [`s2_*.h` header files](https://github.com/google/s2geometry/tree/master/src/s2). Then ask if you have any questions.
