### ISSUE TITLE
I have a polygon and I want to divide it into equal size cells and then I want to write a cloud function where I can input a location the form of Latlng and that will return the the points which are in the cell that is containing the input point  and the adjacent cells. Can anybody help me with this please

### ISSUE THREAD

**Issue by nani-samireddy** [google/s2geometry#140]

**Comment by jmr** [comment]
I'm not sure what you mean by "a cloud function" or "the points which are in the cell that is containing the input point", but maybe something like:
* Use `S2RegionCoverer` with `set_fixed_level` to get the cells
* put them in a `std::unordered_set<S2CellId>`
* iterate over adjacent cells with `S2CellId::AppendAllNeighbors`
* check whether those are in the map

Using `set_fixed_level` will produce a large output for large polygons and high levels, so you don't usually want to do that. There's probably a better way of solving your problem, but I don't have the bigger picture.

**Comment by nani-samireddy** [comment]
I mean I have cloud function that takes a latlng point from Google map and
I have list of latlng points with me.. so now I want get a list of points
which are within 5km distance to the point I got..
