### ISSUE TITLE
Bug in s1interval intersection

### ISSUE THREAD

**Issue by mskd12** [google/s2geometry#148]
Here's a simple piece of code that seems to provide an unexpected output:

```
    S1Angle a1 = S1Angle::Degrees(-162);
    S1Angle a2 = S1Angle::Degrees(82);
    S1Angle a3 = S1Angle::Degrees(-38);
    S1Interval int1(a1.radians(), a2.radians());
    S1Interval int2(a3.radians(), a1.radians());
    cout << int1.Intersection(int2) << endl;
````

It should output the interval [-38, 82]. Instead it outputs [-38, -162].

Any help is appreciated.

**Comment by jmr** [comment]
See the [`S1Interval::Intersection` docs](https://github.com/google/s2geometry/blob/33f25fb3721a69e5320e658978ec932b26725fd6/src/s2/s1interval.h#L175).

```
  // Return the smallest interval that contains the intersection of this
  // interval with "y".  Note that the region of intersection may
  // consist of two disjoint intervals.
```

This is working as intended.

The intersection of your two intervals is actually `-162 ∪ [-38, 82]`, so `[-38, -162]` is the smallest interval containing that.

This is somewhat subtle and I actually spent a while writing test cases before checking the docs.

**Comment by mskd12** [comment]
Ah, interesting. I'm looking for an exact intersection, which as you point out might involve several intervals. Is there a class that provides this functionality? If not, any ideas / thoughts about how I can go about it without rewriting a different S1Interval class.
