### ISSUE TITLE
Edge crossing

### ISSUE THREAD

**Issue by DinosL** [google/s2geometry#156]
Hello,

I am getting an edge crossing error ``` ERROR Edge 33 crosses edge 37 ``` . The coordinates of the object are below and I cannot understand which edge crosses. I also visualised it [here](https://www.keene.edu/campus/maps/tool/) and I cannot find a crossing edge. Is there something that I don't understand?

```
-95.0535 37.7461
-95.0538 37.7458
-95.054 37.7457
-95.0542 37.7455
-95.0544 37.7454
-95.0546 37.7451
-95.0548 37.7449
-95.0549 37.7448
-95.055 37.7446
-95.055 37.7443
-95.0552 37.7441
-95.0561 37.743
-95.0566 37.7425
-95.0567 37.7423
-95.0567 37.7422
-95.0567 37.742
-95.0567 37.7418
-95.0568 37.7417
-95.057 37.7415
-95.057 37.7413
-95.057 37.7412
-95.0569 37.7411
-95.057 37.741
-95.0571 37.7409
-95.0571 37.7407
-95.0571 37.7404
-95.0572 37.7401
-95.0573 37.7398
-95.0573 37.7393
-95.0572 37.7391
-95.0572 37.739
-95.0572 37.7388
-95.0573 37.7386
-95.0574 37.7384
-95.0577 37.7382
-95.0578 37.7379
-95.0581 37.7375
-95.0584 37.7367


```

**Comment by DinosL** [comment]
Is there a way to just omit the items which have crossing edges? I tried using an exception but it is not working. I also tried to preprocess the data with a python script but the python documentation is so poor that I cannot even build a loop,

**Comment by jmr** [comment]
It's hard to say without having seen your code. I don't even know what functions you're calling. You could try adding more logging to the function generating the error message.

Edge 33 is between vertices 33 and 34 (everything zero-index).

**Comment by DinosL** [comment]
```

    vector<S2Point> window;
    window.push_back(S2LatLng::FromDegrees(s.xStart,s.yStart).ToPoint());
    window.push_back(S2LatLng::FromDegrees(s.xStart, s.yEnd).ToPoint());
    window.push_back(S2LatLng::FromDegrees(s.xEnd, s.yEnd).ToPoint());
    window.push_back(S2LatLng::FromDegrees(s.xEnd, s.yStart).ToPoint());

    S2Polygon a(make_unique<S2Loop>(window));

    vector<S2Point> obj;
    size_t size = polygon.geometry.size();
    for(int i = 0; i < size ; i++)
    {
        Coordinates point = polygon.geometry.at(i);
        obj.push_back(S2LatLng::FromDegrees(point.x,point.y).ToPoint());
    }
    S2Polygon b(make_unique<S2Loop>(obj));

    if(a.Intersects(&b))
    {
        return 1;
    }
    return 0;

```

I also tried to use .Normalize() but no luck.

**Comment by jmr** [comment]
You appear to be drawing a straight line, broken up into segments. An `S2Loop` connects the last and first vertices (this is edge 37), so this intersects the others.

**Comment by jmr** [comment]
I haven't heard anything in 3 weeks. Reopen if there's still a problem.
