### ISSUE TITLE
Unable to create objects of S2Polyline and S2Polygon

### ISSUE THREAD

**Issue by hoi4** [google/s2geometry#16]
Hi,

when trying to create objects of S2Polyline or S2Polgon I get the following error:

`undefined reference to 'S2Polyline::S2Polyline()'
undefined reference to 'S2Polyline::Init(std::vector<S2LatLng, std::allocator<S2LatLng> > const&)'
undefined reference to 'S2Polyline::~S2Polyline()'
undefined reference to 'S2Polyline::~S2Polyline()'
`

The code I am using is simply this:
`std::vector<S2LatLng> vertices; 
S2Polyline polyline;
polyline.Init(vertices);`

The implementation of the declared functions in the header files (s2polyline.h and s2polygon.h) seems to be missing.

Thank you in advance
Best regards

**Comment by ericveach** [comment]
Those functions are implemented in the .cc files.  Are you sure that you
are linking with the library?

**Comment by hoi4** [comment]
It was a configuration fault in my cmake file.

Sorry to have bothered you and thank you very much!
