### ISSUE TITLE
Trying to decode a polygon with no points fails unexpectedly

### ISSUE THREAD

**Issue by benhannel** [google/s2geometry#163]
If you encode a polygon with no points with `s2shapeutil::CompactEncodeShape` it returns true, presumably indicating success, but then trying to decode the output returns nullptr, presumably indicating failure. If this is a valid polygon representable in S2, then it should be possible to encode it and decode it and maintain fidelity. If it is not, then it should fail at construction time. Using `FastEncodeShape` rather than `CompactEncodeShape` causes decoding to succeed.

To reproduce:
```
    vector<unique_ptr<S2Loop>> loops;
    loops.push_back(make_unique<S2Loop>(vector<S2Point>()));
    auto inputShape =
            S2Polygon::OwningShape(make_unique<S2Polygon>(std::move(loops)));

    Encoder encoder;
    bool success = s2shapeutil::CompactEncodeShape(inputShape, &encoder);
    EXPECT_TRUE(success);  // Succeeds

    Decoder decoder(encoder.base(), encoder.length());
    auto outputShape =
            s2shapeutil::FullDecodeShape(inputShape.type_tag(), &decoder);
    EXPECT_NE(outputShape, nullptr);  // Fails
```

**Comment by jmr** [comment]
Loops either need to have at least 3 points, or be constructed with `kEmpty` or `kFull`.
https://github.com/google/s2geometry/blob/c69344a9d9de0371294ca0143c510f89dcadb2f1/src/s2/s2loop.h#L67

You're probably not in compiling in debug mode; here's what I get:
```
E1214 00:48:21.277922    4602 s2polygon.cc:163] Loop 0: Non-empty, non-full loops must have at least 3 vertices
F1214 00:48:21.278101    4602 s2polygon.cc:294] Check failed: IsValid()
```

https://github.com/google/s2geometry/blob/c69344a9d9de0371294ca0143c510f89dcadb2f1/src/s2/s2polygon.cc#L311
