### ISSUE TITLE
curious if anyone has thought about porting some of the cell functionality to mysql

### ISSUE THREAD

**Issue by victusfate** [google/s2geometry#178]
specifically interested in group by parent cell queries ie compute a given s2cell ids ith level parent directly in sql
I got as far as working on recreating the 64bit  representation from the source 

```
(id_ & (~new_lsb + 1)) | new_lsb
```

so far the geo queries work great for cell id between min/max levels

**Comment by jmr** [comment]
This is more a question for mysql/mongodb/arangodb/....
