### ISSUE TITLE
Please make python link conditional on an cmake variable

### ISSUE THREAD

**Issue by yurivict** [google/s2geometry#180]
It should be possible to turn off python bindings.

Further, python bindings should be buildable separately from the C++ library, because system can have several python versions installed at the same time, and each one can have s2geometry bindings built for it.

**Comment by spaetz** [comment]
I wanted to package s2geometry as a library for Debian, and requiring python include files even when not needing the python interface was a killer. Some inspiration to make python optional can be found here: https://github.com/rinigus/s2geometry/blob/main/CMakeLists.txt

Sorry, I don't know enough CMake magic to really provide a nice patch.

**Comment by spaetz** [comment]
Sorry, I see there is even a MR to provide this at https://github.com/google/s2geometry/pull/170

**Comment by jmr** [comment]
Fixed by #189
