### ISSUE TITLE
Please make a new release 0.10 (and tag it)

### ISSUE THREAD

**Issue by spaetz** [google/s2geometry#187]
I would love to package libs2 for Debian (in fact I have a local packaging repo at at https://salsa.debian.org/Mobian-team/puremaps-packaging/s2geometry-deb), but would love to package a nice reference release, instead of a random commit hash. The last formal release is 2 years ago, libs2 already announces itself as 0.10.0 to the world, so can we make a release please?

Would be appreciated, and thanks for s2geometry!

**Comment by jmr** [comment]
There aren't that many changes since 0.9. Maybe it was a mistake to increase the version number while 0.10 is still in development.

I want to remove the internal absl before releasing 0.10. How do you package absl? Only the LTS releases?

**Comment by spaetz** [comment]
I can't speak about policies, but current Debian testing and unstable contain:
0~20200923.3-2 https://packages.debian.org/source/testing/abseil
For my naive packaging I was simply using the bundled version...

**Comment by jmr** [comment]
I removed the internal absl. I should probably switch from gflags to absl flags, too. Can you try to package a recent hash and I'll tag it if it's good?

**Comment by jmr** [comment]
With #217 there are also a bunch of new files. I have a few more cleanups in mind, then I'll tag 0.10.

**Comment by spaetz** [comment]
I have not tried it yet (sorry), but sounds good.

**Comment by jmr** [comment]
The absl might have to be updated. I'm not sure when `find_package(absl)` support was added.

**Comment by jmr** [comment]
https://github.com/google/s2geometry/releases/tag/v0.10.0-2022.02.23.00

**Comment by spaetz** [comment]
Thank you very much and sorry for not responding earlier. I will try and see if I get this cleanly packaged as a .deb.

**Comment by jmr** [comment]
https://github.com/google/s2geometry/releases/tag/v0.10.0
