### ISSUE TITLE
set_fixed_level not adhering to fixed level

### ISSUE THREAD

**Issue by cbeddow** [google/s2geometry#197]
I am setting a fixed level of 15, then running regionCoverer, and checking the output. Here is a visual of what I get, with other levels, the smallest visible one on edges being 15. When I print the levels of all cells, I get several at level 14. 

How can I force it to produce only level 15? Otherwise what I am looking for is splitting each 14 or other level cell into children then retrieving the geometry.

![image](https://user-images.githubusercontent.com/10554922/131864662-85393b73-fe5b-4f60-ade0-b0de65902f16.png)

**Comment by eengle** [comment]
Can you share an example of the code that is producing the covering?

**Comment by cbeddow** [comment]
@eengle using PyWraps:

```
urbans2 = []
fixed_level = 16
test = None
for feature in urban_geom['features']:
    geom = list(chain.from_iterable(feature['geometry']['coordinates']))
    minll = [min(lng for lng,lat in geom),min(lat for lng,lat in geom)]
    maxll = [max(lng for lng,lat in geom),max(lat for lng,lat in geom)]
    bbox = s2.S2LatLngRect(
        s2.S2LatLng.FromDegrees(minll[1],minll[0]),
        s2.S2LatLng.FromDegrees(maxll[1],maxll[0])
    )
    bbox_cover = s2.S2RegionCoverer()
    bbox_cover.set_max_cells(1000000)
    bbox_cover.set_fixed_level(fixed_level)
    bbox_cells = bbox_cover.GetCovering(region=bbox)
    if len(urbans2) > 0:
        urbans2[0] = s2.S2CellUnion(urbans2[0].cell_ids() + bbox_cells)
    else:
        urbans2.append(s2.S2CellUnion(bbox_cells))
```

The urban_geom geojson it is iterating over is a set of polygons, here's a small sample:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": 0
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              8.52848053,
              47.38319635
            ],
            [
              8.528979337,
              47.382979268
            ],
            [
              8.528686389,
              47.382597941
            ],
            [
              8.528851932,
              47.382539541
            ],
            [
              8.528971206,
              47.382700779
            ],
            [
              8.529435815,
              47.382500608
            ],
            [
              8.529332131,
              47.382380857
            ],
            [
              8.529876955,
              47.382287724
            ],
            [
              8.529989021,
              47.382216951
            ],
            [
              8.529897742,
              47.382110196
            ],
            [
              8.530942546,
              47.381610812
            ],
            [
              8.530843137,
              47.381508143
            ],
            [
              8.531174054,
              47.381311146
            ],
            [
              8.531437917,
              47.381505021
            ],
            [
              8.530270653,
              47.382118823
            ],
            [
              8.530003689,
              47.382388803
            ],
            [
              8.530199826,
              47.382534093
            ],
            [
              8.529837728,
              47.382708611
            ],
            [
              8.529902101,
              47.382800325
            ],
            [
              8.528411211,
              47.383412465
            ],
            [
              8.528315322,
              47.383249414
            ],
            [
              8.52848053,
              47.38319635
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": 1
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              8.530650018,
              47.38393879
            ],
            [
              8.530762168,
              47.384000933
            ],
            [
              8.530540466,
              47.384170282
            ],
            [
              8.530540466,
              47.383963534
            ],
            [
              8.53061188,
              47.383917621
            ],
            [
              8.530650018,
              47.38393879
            ]
          ]
        ]
      }
    }
  ]
}
```

**Comment by jmr** [comment]
I think `S2CellUnion` is [merging in the constructor](https://github.com/google/s2geometry/blob/master/src/s2/s2cell_union.h#L60). Look at the return value from `GetCovering` directly and see if it still happens.

**Comment by cbeddow** [comment]
@jmr ah I see, that makese sense. So my thinking was:

1) the region_coverer returns a cell union
2) if I run region_coverer on several rectangular areas, I end up with several cell unions
3) I should make a union of the cell unions to merge them together

Is there a way I can merge the multiple cell unions of the region coverer, with has fixed level of 16 always, without the cells merging again?

I will try another way of doing this as well, but I'm hoping for  a most efficient way of having a total grouping of the size 16 cells so I can then test another geometry for intersection without having to pairwise compare every individual covering. Alternatively, I am just looking to achieve a region covering for an irregular shaped region (think like shape of Hawaii or the Great Lakes or Japan) without having to first make it a rectangular region that gives me cells which do not intersect the thing covered, and then again having to pairwise remove the cells that do not intersect the original shape.

**Comment by jmr** [comment]
> Is there a way I can merge the multiple cell unions of the region coverer, with has fixed level of 16 always, without the cells merging again?

Use a python `set()`.

> I will try another way of doing this as well, but I'm hoping for a most efficient way of having a total grouping of the size 16 cells 

The most efficient way isn't to use `set_fixed_level`, but to use variable levels.

> so I can then test another geometry for intersection without having to pairwise compare every individual covering. 

If you're using coverings, you're not getting an exact answer. If that's fine, use `S2CellUnion::Intersects`. Otherwise, use `S2BooleanOperation`. You might have to swig-wrap it.

**Comment by jmr** [comment]
You can also re-split cells with `S2CellUnion::Denormalize`.
