### ISSUE TITLE
Why doesn't s2 support multiPoint,multPolyline and multiPolygon?

### ISSUE THREAD

**Issue by jievince** [google/s2geometry#198]
OGC defines them.

**Comment by eengle** [comment]
S2 uses a slightly more general data model than the OGC "Simple Features" specification, which is perhaps what you're referring to. In OGC terms, S2 defines point, line, and multipolygon types, and the common intersects/contains/etc operations are provided on them.

More complex general operations on collections of these types are ill-defined or outright illegal in OGC, and unevenly implemented in e.g. GEOS or JTS, but feel free to reopen this ticket if you have specific questions about how to accomplish something with S2.

**Comment by jievince** [comment]
Ok, got it.
I am reading the source code of arangodb geo spatial. I found that they implement s2MultiPointRegion, s2multiPolyline by inheriting s2Region. 
> More complex general operations on collections of these types are ill-defined or outright illegal in OGC

So as you say, it's not a good idea to do it like this?
