### ISSUE TITLE
Why Polyline::Contains(S2Point) is not numerically well-defined?

### ISSUE THREAD

**Issue by jievince** [google/s2geometry#199]
In math, testing if a point is on a line is easy.

**Comment by jmr** [comment]
`S2Point`s have finite precision. It's not really useful or interesting to ask if a point is on a line. Use the distance to the line with a threshold if you want to do that.

**Comment by jievince** [comment]
Sorry @jmr, I didn't find a function in the S2 library that defines the shortest distance from a S2Point to a Polyline.

**Comment by jievince** [comment]
Seems `S2Polyline::Project` is what I want...
