### ISSUE TITLE
Could not call hidden method

### ISSUE THREAD

**Issue by nowbug** [google/s2geometry#2]
Hi, I am fortunate to be able to use this S2 algorithm. I have to say that this is a great project. I admit I underestimated it. But when I use the swig python version, I can not use the method I want, pywraps2.S2RegionCoverer (), I can not use the set_min_level (), set_max_level (), set_max_cells () I was expecting because I found my project file Without these, I do not know where the problem is. If you can help me, I will be grateful.

**Comment by jmr** [comment]
In C++ we moved set_max_level from S2RegionCoverer to S2RegionCoverer::Options.  It looks like [s2_common.i](https://github.com/google/s2geometry/blob/a2efd83f743f5a8d2a8b4ef1663c5703cf6735a2/src/python/s2_common.i#L439) wasn't updated though. I'll look at a fix.

**Comment by nowbug** [comment]
Thank you for your timely fix, for a better future, Cheers.

**Comment by jmr** [comment]
This should be working [now](https://github.com/google/s2geometry/blob/f204ff825ae3650952e872e327c2bf2686fd5599/src/python/s2_common.i#L186).
