### ISSUE TITLE
What is the semantics of Contains?

### ISSUE THREAD

**Issue by jievince** [google/s2geometry#200]
```
bool S2Polygon::Contains(const S2Point& p) const;
bool S2Polygon::Contains(const S2Polyline& b) const;
```
If the point or polyline is just on the boundary of the polygon, will this function return true or false?

Postgis defines ST_covers and ST_contains to distinguish them( if and only if no points of B lie in the exterior of A, and at least one point of the interior of B lies in the interior of A(https://postgis.net/docs/ST_Contains.html),
> ST_covers(a, b): no point of b is in the exterior of a;
> ST_contains(a, b): no point of b is in the exterior of a, and at least one point of b is in the interior of a.
So a polygon doesn't ST_contains its boundary but ST_covers it.

**Comment by jmr** [comment]
You probably want to use `S2BooleanOperation` you can control whether the boundaries are included or not.

Leaving this open until we document this better.

**Comment by jievince** [comment]
Hi @jmr, seems that `S2BooleanOperation` provides a very flexible way to control the boundary.
But it's a little complex for me. 
I want to use these functions:
```
bool S2Polygon::Contains(const S2Point& p) const;
bool S2Polygon::Contains(const S2Polyline& b) const;
```
And I want to know if the point or polyline is just on the boundary of the polygon, will these functions return true or false?

**Comment by jmr** [comment]
See [the documentation](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L501).
