### ISSUE TITLE
Does Google's BigQuery use S2 to support geo spatial?

### ISSUE THREAD

**Issue by jievince** [google/s2geometry#203]
I have a look at [bigquery's gis](https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions)  related doc, and it seems to use the s2 library.
It supports OGC multiPoint/multiPolygon/multiPolygon.
However, according to https://github.com/google/s2geometry/issues/198, these collection types are ill-defined?

**Comment by eengle** [comment]
The BigQuery Geography features do use S2, among many other libraries.

Re #198, no, it isn't that the collection types are ill-defined, it's that some operations on the types are ill-defined. The simple features spec really does focus on simple features, eliminating the more complicated potential operations in favor of a simpler model.
