### ISSUE TITLE
The S2Polyline/S2Polygon's validaty checking

### ISSUE THREAD

**Issue by jievince** [google/s2geometry#204]
Hi, everyone,
I'm writing a geo implementation that uses the s2 library for a database.
Some problems bother me. So I came to ask for help.

Many geo databases like PostGIS/SQL server/cockroach allow invalid geo data to be stored in the database. Therefore, some geo calculations like st_distance done on these invalid data may have undefined behavior. If users want to prevent the UB, they need to use `ST_IsValid` to filter the invalid data.  I think it's complicated for the user. So I decided to check the validity first and prohibit illegal data from entering the database.  *This is basically the same as BigQuery.*
This actually brings forward the validity check at calculation time to insert data.

However, it seems *expensive* to check the validity.
eg. For a LineString, it can't self-pollinate, and for a Polygon, the exterior loop must contain any of the interior loop.
Seems that In order to check if the user input wkt/wkb is valid to build s2 data, I must construct an S2Polyline/S2Polygon firstly from the user input.

Thus, to check the validity, a s2 data is constructed. And to store the geo data in the database storage, I need to convert it to a wkb format. And when later need to do geo calculations on it, I need to read the wkb from the storage and convert it to s2 data back. *That's what bothers me.!* *The s2 data is built twice! First time for validity checking, and the second time for geo calculations.* 

1. When insert geo data:
`insert into geo_table(geo) values ('ST_Geogfromtext('LineString(0 0, 1 1, 2 2)')')`
`wkt->s2 data(Just for validity checking)->wkb(Storing it as wkb in the kv storage)`
2. And when do geo calculations:
`select st_intersects(geo, st_point('3 8')) from geo_table`
`wkb(read from the kv storage)->s2 data(Use the function of S2 to do the calculation)`

Am I doing the right thing? Is there a more efficient way? Whether S2 must be built twice?
Any answer would be greatly appreciated

**Comment by eengle** [comment]
Well at a minimum you want an encoding that is lossless under a roundtrip,
so you can validate in S2, store in the encoded form, and know that when
you later load and decode the data back into S2, that it's still valid so
you don't have to validate it again.

One approach to that is to use S2's encodings. These are generally
backward-compatible so you won't lose the ability to decode data later.
E.g. S2Polygon::Encode
<https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L677>.

Another option is to create your own encoder / decoder, e.g. write a list
of loops, where each loop is a list of vertices, where each vertex is the
x,y,z double coordinates.

Good luck on your project, and kind regards,

- Eric

**Comment by jievince** [comment]
Hi @eengle, thank you very much for your advice!!
I'd like to talk a little bit more about the two approaches you mentioned.
For the first approach, Using the `Encode` method of S2 as storage consists of two points that worry me:
1. S2's data structure stores some additional information. eg. S2Polygon, it not only stores the raw loop information, but it also stores some data related to the in-memory index, which is used to speed up the calculation of Intersects and so on. This will lead to serialized network I/O overhead and storage layer overhead, especially for a database that stores computations separately.
2. The data input of s2's data structure is not corresponding. For example, the original input is a pair of latitude and longitude, while s2 stores radians. This causes an additional conversion when the user uses a function like `st_astext`, these functions don't need a computation based on s2 data, they just need a conversion based on the original data.
*So for those two reasons, I think it's better to store it as WKB, what do you think?*

For the second solution, I don't quite understand this approach. Do you mean I still construct S2 for validation, but use custom encode/decode methods(Just like implementing an S2 to WKB encode/decode method?) for S2 data for serialization transfer and storage on storage media? If so, it's similar to the confusion I mentioned in the question:
```
When insert geo data:
insert into geo_table(geo) values ('ST_Geogfromtext('LineString(0 0, 1 1, 2 2)')')
wkt->s2 data(Just for validity checking)->wkb(Storing it as wkb in the kv storage)
And when do geo calculations:
select st_intersects(geo, st_point('3 8')) from geo_table
wkb(read from the kv storage)->s2 data(Use the function of S2 to do the calculation)
```
`This still results in s2 data being constructed twice!!`
I am looking forward to your reply again!

**Comment by jievince** [comment]
Sorry @eengle, I may have written too much... I want to cut them down to 2 key sentences:
1. I want to reduce network IO and storage overhead, so I don't want to use S2 in either process. I prefer to use wkb to achieve it.
2. I want to validate the user input data when do inserting and reject the invalid ones to be inserted into the database. In order to verify the validity, I had to construct S2 and call isValid method of S2. Then, because of the first point, I didn't want to use S2 directly in the network transport and storage layer, so after the validity checking, I needed to convert them into WKB and then transfer them to the storage node over the network and persist them to the storage layer. Then when I do calculations like ST_intesects, I need to read these WKB out of the storage layer and construct S2 for the calculation, **which results in S2 being constructed twice!!**
Is there a way to do both?

**Comment by eengle** [comment]
Well, the network IO and storage overhead with WKB would be better than if
you stored x,y,z doubles instead of lng,lat doubles, but far higher than if
you snapped your S2Points to level 30 cell centers and used the COMPACT
encodings. In that case, you can get quite good compression, 10:1 and
better has been observed for complex polygons.

Broadly, the basic goals you're expressing are just incompatible. The
fundamental data model of S2 is not longitude latitude based, so storing
anything but S2Points will require converting the data more than once. If
you store the data as WKB, then you must convert it to S2 in order to do S2
things with it.

By comparison, JTS / GEOS and other WKB-capable systems can parse WKB just
fine, but they also have to convert the data into their own internal data
model. So the general best practice for avoiding this double conversion
problem is to store data that's as close to the encoding used by your
operations as you can afford.

Kind regards,

Eric

**Comment by jievince** [comment]
Thank you very much for your explanation!
