### ISSUE TITLE
Information: Library S2 Geometry in Kotlin exists

### ISSUE THREAD

**Issue by jbordeau** [google/s2geometry#207]
Hi,
we have a library in kotlin almost up to date to the original library.
https://github.com/Enovea/s2-geometry-kotlin

**Comment by jmr** [comment]
Send a PR to add it to [README.md](https://github.com/google/s2geometry#other-s2-implementations).

**Comment by jbordeau** [comment]
[check this PR](https://github.com/google/s2geometry/pull/208)
