### ISSUE TITLE
Create Spatial Index using Neural Network

### ISSUE THREAD

**Issue by carlosg-m** [google/s2geometry#250]
Consider a Skip-gram model from NLP.
Apply the same concept to pairs of points in ECEF, instead of Cosine distance use Euclidean distance.
Get extremely accurate multidimensional projection (>2 dimensions) that works for the entire globe. In this case the L2 norm between any two vectors should be approximately equal to the geodesic distance.
Use the projection as base to hash geometries and so on (similar to encoding sentence merging embedding of each word).

The idea here, if possible, would be to project the surface of a manifold into a high dimensional Cartesian plane.

https://carlostgameiro.medium.com/disrupt-spatial-analysis-642eeb360493

**Comment by jmr** [comment]
S2 makes the approximation that the Earth is a sphere. It also provides indexing and closest queries. We also don't want to take dependencies on TensorFlow. Your idea would probably be best implemented as its own library.
