### ISSUE TITLE
Does S2 support Windows?

### ISSUE THREAD

**Issue by Leedehai** [google/s2geometry#252]
Hi, I noticed there are several [closed issues](https://github.com/google/s2geometry/issues?q=windows+is%3Aclosed) that relate to Windows, and based on their contents it appears S2 supports Windows. Code in the [ae470b7](https://github.com/google/s2geometry/commit/ae470b730441ebe7b0bf630527038acc219b2eb9) version committed on April 11, 2022 doesn't contain `getrusage()` or headers that indicate POSIX like `unistd.h`.

However, the official website http://s2geometry.io/about/platforms says `Windows is not supported at this time` and that POSIX `getrusage()` is needed. 

Could you elaborate on why Windows isn't supported? Or, is the doc out of date? Thanks!

**Comment by jmr** [comment]
Documentation appears to be out of date. Windows is certainly less tested, but may work. Try it and let us know.

**Comment by MBkkt** [comment]
We use s2 on windows in ArangoDB

**Comment by jmr** [comment]
Looks like s2geometry.io is just out of date.
