### ISSUE TITLE
Cannot build with cmake -DGTEST_ROOT=/usr/src/gtest -DCMAKE_PREFIX_PATH=/path/to/absl/install -DCMAKE_CXX_STANDARD=11 ..

### ISSUE THREAD

**Issue by Jiboxiake** [google/s2geometry#255]
I tried to run this command but it keeps throwing
```
CMake Error at CMakeLists.txt:70 (find_package):
  By not providing "Findabsl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "absl", but
  CMake did not find one.

  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
```
I have followed the steps pointed to by the link to install abseil except I couldn't build with /temporary/build/abseil-cpp but only with /build/abseil-cpp. I don't know if this is related.

**Comment by jmr** [comment]
What are the exact command lines you used to configure/compile/install absl/s2?

**Comment by jmr** [comment]
You need to replace `/path/to/absl/install` with the path that you actually used to install absl -- whatever you used for `CMAKE_INSTALL_PREFIX` with absl.  

Don't look at https://s2geometry.io/about/platforms; it hasn't been updated to talk about absl.  

https://github.com/google/s2geometry/blob/master/README.md#building has the s2 side of things. https://abseil.io/docs/cpp/tools/cmake-installs is for absl.

**Comment by craigds** [comment]
I also struggled with the build instructions; with no background for what googletest or abseil are or why they're required it's quite confusing.

In case it helps point you in the right direction, I finally managed to write this Dockerfile which builds a python wheel of our fork of s2-py, including installing and building abseil and s2geometry: https://github.com/koordinates/s2-py/blob/master/Dockerfile

**Comment by Jiboxiake** [comment]
Thank you all! That helps.
