### ISSUE TITLE
S2Polyline in Python wrapper doesn't have method MayIntersect

### ISSUE THREAD

**Issue by seanzxx** [google/s2geometry#26]
I cloned and built the latest master branch. 
I could find the MayIntersect method in the S2Polyline object however it is in the CPP source code. 

Help needed to figure out the way to call this method in Python.

Thanks a lot.

**Comment by jmr** [comment]
Ok, I'll add this soon.

**Comment by jmr** [comment]
Until I do that, what are you using `MayIntersect` for? 

You could try `s2.S2Polygon(cell).Intersects(polyline)`.

`return True` is a valid implementation, so you could also assume intersection is always possible.

**Comment by jmr** [comment]
I added [`S2Polyline.MayIntersect`](https://github.com/google/s2geometry/blob/master/src/python/s2_common.i#L468) and a few more. Please try again and reopen this bug if it doesn't work.
