### ISSUE TITLE
-DCMAKE_CXX_STANDARD=17 doesn't work

### ISSUE THREAD

**Issue by jievince** [google/s2geometry#270]
The cache of build is cleared, and I specify `-DCMAKE_CXX_STANDARD=17`, but s2 still use c++11 to compile.
But if I change the line `set(CMAKE_CXX_STANDARD 11)` to `set(CMAKE_CXX_STANDARD 17)` in CmakeLists.txt, it works.

**Comment by jievince** [comment]
> The cache of build is cleared, and I specify `-DCMAKE_CXX_STANDARD=17`, but s2 still use c++11 to compile. But if I change the line `set(CMAKE_CXX_STANDARD 11)` to `set(CMAKE_CXX_STANDARD 17)` in CmakeLists.txt, it works.

The cmake flag will make affect when changing `set(CMAKE_CXX_STANDARD 11)`   to `option(CMAKE_CXX_STANDARD 11)`

**Comment by jmr** [comment]
Could you open a PR to fix it?
