### ISSUE TITLE
fails to build on on ppc64el

### ISSUE THREAD

**Issue by spaetz** [google/s2geometry#279]
Hi,
s2geometry is in Debian, great. However, it fails to build on 2 architectures, and I have no clue what could be wrong, or how to fix it. (This is tag/v0.10.0,  BTW)

The Debian issue is at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023961 pointing to the build protocol at:
https://buildd.debian.org/status/fetch.php?pkg=s2geometry&arch=ppc64el&ver=0.10.0-2&stamp=1667081576&raw=0

The relevant bit seems to be:
```
/<<PKGBUILDDIR>>/src/s2/s2edge_crossings.cc: In instantiation of ‘bool S2::internal::GetStableCrossProd(const Vector3<T>&, const Vector3<T>&, Vector3<T>*) [with T = long double]’:
/<<PKGBUILDDIR>>/src/s2/s2edge_crossings.cc:127:54:   required from here
/<<PKGBUILDDIR>>/src/s2/s2edge_crossings.cc:115:31: error: ‘(6.15348059642740421245081038903225e-15l / 5.40431955284459475358983848622456e+16l)’ is not a constant expression
  115 |       (32 * kSqrt3 * DBL_ERR) /
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^
  116 |       (kRobustCrossProdError.radians() / T_ERR - (1 + 2 * kSqrt3));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/<<PKGBUILDDIR>>/src/s2/s2edge_crossings.cc: In instantiation of ‘bool S2::GetIntersectionSimple(const Vector3<T>&, const Vector3<T>&, const Vector3<T>&, const Vector3<T>&, Vector3<T>*) [with T = long double]’:
/<<PKGBUILDDIR>>/src/s2/s2edge_crossings.cc:485:28:   required from here
/<<PKGBUILDDIR>>/src/s2/s2edge_crossings.cc:458:10: error: ‘(1.2e+1l / 7.20575940379279305358983848622456e+16l)’ is not a constant expression
  458 |       12 / (kIntersectionError.radians() / T_ERR - (2 + 2 * kSqrt3));
      |       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/s2.dir/build.make:653: CMakeFiles/s2.dir/src/s2/s2edge_crossings.cc.o] Error 1

```

**Comment by spaetz** [comment]
**‘(6.15348059642740421245081038903225e-15l / 5.40431955284459475358983848622456e+16l)’ is not a constant expression**

?

**Comment by spaetz** [comment]
Second issue on s390x is:
```
[ 96%] Building CXX object CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o
/usr/bin/c++ -DABSL_MIN_LOG_LEVEL=1 -Ds2_EXPORTS -I/usr/include/python3.10 -I/<<PKGBUILDDIR>>/src -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -Wno-attributes -Wno-deprecated-declarations -std=c++11 -MD -MT CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o -MF CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o.d -o CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o -c /<<PKGBUILDDIR>>/src/s2/util/math/exactfloat/exactfloat.cc
/<<PKGBUILDDIR>>/src/s2/util/math/exactfloat/exactfloat.cc:144:20: error: #elif with no expression
  144 | #elif IS_BIG_ENDIAN
      |                    ^
/<<PKGBUILDDIR>>/src/s2/util/math/exactfloat/exactfloat.cc:148:2: error: #error one of IS_LITTLE_ENDIAN or IS_BIG_ENDIAN should be defined!
  148 | #error one of IS_LITTLE_ENDIAN or IS_BIG_ENDIAN should be defined!
      |  ^~~~~

```

**Comment by jmr** [comment]
This looks like a compiler bug or quality-of-implementation issue.  From a bit of playing with godbolt, `long double` `constexpr`s don't work with `*` or `/`, but work with `+` and `-`.

https://godbolt.org/z/WYz5fY538

This works fine on everything but PPC that I tried. It also works with PPC clang, but not PPC gcc. Could you report this to gcc and see what they say?

For reference, here's the real code: https://github.com/google/s2geometry/blob/2ff824474f0c4dfb157a0d056e4a6bb76bfa690f/src/s2/s2edge_crossings.cc#L115

**Comment by spaetz** [comment]
Just for completeness' sake: Upstream bug filed at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107745

Let's see what gcc makes of it.

**Comment by jmr** [comment]
Just wondering, does clang support this architecture, and does the code compile without workarounds with it? @spaetz

**Comment by spaetz** [comment]
Sorry, I don't even own that architecture, just reporting on what the Debian build system does which attempts to build on basically all arches. I know next to nothing about clang, I am embarrassed to admit.

**Comment by barracuda156** [comment]
@jmr Until/unless GCC addresses that, maybe we could make a fix in the master?

**Comment by jmr** [comment]
Yes, we can do that since it's an easy work-around.  Could you file another bug with gcc and make it clear that this is fails-to-compile-valid, not missed-optimization.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107745#c4 mentions "powerpc64le-linux is phasing that out and switching to IEEE quad instead". Are you seeing this on Linux, OS X Snow Leopard (~10 years past EOL), or something else?

**Comment by barracuda156** [comment]
@jmr 

> Yes, we can do that since it's an easy work-around. Could you file another bug with gcc and make it clear that this is fails-to-compile-valid, not missed-optimization.

The original ticket tracks the matter, and had some responses today: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=19779

> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107745#c4 mentions "powerpc64le-linux is phasing that out and switching to IEEE quad instead". Are you seeing this on Linux, OS X Snow Leopard (~10 years past EOL), or something else?

I get this on OS X, yeah. But the same gonna be the case on OpenBSD, for example, etc.

**Comment by jmr** [comment]
Worked around the gcc bug in 84bfd2c.

**Comment by barracuda156** [comment]
> Worked around the gcc bug in 84bfd2c.

@jmr Wow, that’s a massive commit! Thank you, I will try it.

BTW, are we to expect any changes for Big-endian (for better or worse)?

**Comment by jmr** [comment]
See https://github.com/google/s2geometry/issues/316#issuecomment-2039999691 for BE status. No change expected.
