### ISSUE TITLE
Undefined sanitizer issue

### ISSUE THREAD

**Issue by MBkkt** [google/s2geometry#283]
-fsanitize=nullability-arg: Passing null as a function parameter which is annotated with _Nonnull.

https://github.com/google/s2geometry/blob/master/src/s2/util/gtl/compact_array.h#L416

You can add if (old_capacity != 0)

Also if it something like vector with SSO, maybe better to use absl::InlinedVector?

**Comment by MBkkt** [comment]
https://github.com/google/s2geometry/pull/284

**Comment by jmr** [comment]
> Also if it something like vector with SSO, maybe better to use absl::InlinedVector?

`CompactArray` also has space optimizations, hence the "Compact".

**Comment by MBkkt** [comment]
Ok
