### ISSUE TITLE
Is this library thread safe?

### ISSUE THREAD

**Issue by ch541819** [google/s2geometry#3]
Is S2PointIndex thread safe? Should I use mutex when S2PointIndex.Add() and S2ClosestPointQuery.query() are called simultaneously in multithread?

**Comment by ericveach** [comment]
Unless otherwise documented, all S2 classes have the same thread-safety properties as std::vector: const methods are thread-safe, and non-const methods are not thread-safe.

So for example you issue multiple queries at the same time, but updates to the index cannot overlap any other operations.

**Comment by jmr** [comment]
This is documented on [`MutableS2ShapeIndex'](https://github.com/google/s2geometry/blob/8a8746c7f4d4c53e8561e78e6ca380e8d4a0b9d3/src/s2/mutable_s2shape_index.h#L104):

```c++
// Locking is used to ensure that MutableS2ShapeIndex
// has the same thread-safety properties as "vector": const methods are
// thread-safe, while non-const methods are not thread-safe.  This means that
// if one thread updates the index, you must ensure that no other thread is
// reading or updating the index at the same time.
```

@ericveach Should we add something similar on `S2ShapeIndex`? The [`Minimize()` comment](https://github.com/google/s2geometry/blob/8a8746c7f4d4c53e8561e78e6ca380e8d4a0b9d3/src/s2/s2shape_index.h#L256) implies this, but it's easy to miss.

**Comment by ericveach** [comment]
Probably.  Of course someone could write an S2ShapeIndex subtype with
different thread safety properties if desired, but there doesn't seem to be
any harm in documenting that the abstract method is not required to be
thread-safe.

**Comment by jmr** [comment]
Now documented on [`S2ShapeIndex`](https://github.com/google/s2geometry/blob/f77eeb2f328ee3d3929e68a75c6b05144a8749a1/src/s2/s2shape_index.h#L233) as well.
