### ISSUE TITLE
Support Intersects/Contains(polygon/loop) in S2Cap

### ISSUE THREAD

**Issue by brianv0** [google/s2geometry#32]
I was looking at the code, and it'd be nice if I could check if S2Loop was in an S2Cap. Naively, it seems like you can take the existing code for `S2Cap::Contains(const S2Cell& cell)` and `S2Cap::Intersects(const S2Cell& cell, ...)` and just generalize it for an S2Loop, at a minimum, and maybe S2Rect and S2Poly as well. Would this be reasonable? Or is there a better way at handling this?

Obviously an arbitrary S2Region Intersects/Contains S2Region would be ideal, but I wasn't sure if that made sense to the other classes that extend S2Region.

**Comment by ericveach** [comment]
I should also have mentioned that you can test whether an S2Cap intersects
an S2Polygon (in fact, any collection of points, polylines, and polygons)
using S2ClosestEdgeQuery, by testing whether the minimum distance from the
cap center to the geometry is less than or equal to the cap radius.

**Comment by ericveach** [comment]
You can do this using S2FurthestEdgeQuery.  You can actually check whether
any collection of points, polylines, and polygons fits within a given
S2Cap, or alternatively you can compute the minimum radius S2Cap that
contains the given geometry.

For example, to test whether an S2Polygon fits within a given S2Cap, you
can do this:

bool Contains(const S2Cap& cap, const S2Polygon& polygon) {
  S2FurthestEdgeQuery query(&polygon.index());
  S2FurthestEdgeQuery::PointTarget target(cap.center());
  return !query.IsDistanceGreater(&target, cap.radius());
}

This simply checks whether the maximum distance from the cap center to any
point contained by the polygon is greater than the cap radius.

To do this using arbitrary geometry, you would create a MutableS2ShapeIndex
and add the geometry to it, like this:

MutableS2ShapeIndex index;
index.Add(absl::make_unique<S2Polygon::Shape>(&polygon1));
index.Add(absl::make_unique<S2Polyline::Shape>(&polyline1));
index.Add(absl::make_unique<S2Polyline::Shape>(&polyline2));
S2FurthestEdgeQuery query(&index);
... as before ...
