### ISSUE TITLE
ce8e338 breaks MSVC on Windows

### ISSUE THREAD

**Issue by wegylexy** [google/s2geometry#327]
This google3 update ce8e338067b336acc609f48b40fcf81bdf900a6c seems not standard compliant and thus breaks compiling with MSVC.
For instance, there is no `S2Point()` constructor that takes 0 arguments.

**Comment by smcallis** [comment]
That's a very large update, we're going to need more information to hope to debug it.  S2Point definitely has a no-argument constructor, this compiles for me:

```
TEST(Foo, Bar) {
  S2Point baz;
  absl::PrintF("%f %f %f\n", baz.x(), baz.y(), baz.z());
}
```

```
[ RUN      ] Foo.Bar
0.000000 0.000000 0.000000
```

**Comment by jherico** [comment]
It compiles on GCC and Clang because they treat the interaction between the `using Base::Base` declaration and the deletion of a default ctor in the presence of a non-trivial ctor differently.  See https://godbolt.org/z/EPnsMEq8v

**Comment by jmr** [comment]
Reopen #338 if this is not fixed.
