### ISSUE TITLE
After installing s2geometry, CMakeLists.txt failed on "find_package(s2geometry REQUIRED)"

### ISSUE THREAD

**Issue by GoroYeh-HRI** [google/s2geometry#331]
Hello, 
I followed your instructions for installing s2geometry and I confirmed it is installed under `/usr/local/include`
![image](https://github.com/google/s2geometry/assets/137837175/371f07fa-662d-4ede-aa8d-7d52d29cba1c)
![image](https://github.com/google/s2geometry/assets/137837175/f1c3e42c-2e2e-4d03-8736-113f14551067)

However, when I'm trying to use s2geometry in my another Cmake project, in CMakeLists.txt I wrote `find_package(s2geometry REQUIRED)`
and run `cmake ..`.
The compiler has error about this:
![image](https://github.com/google/s2geometry/assets/137837175/a270562c-5114-457f-8b42-dad182badbad)

Also, once I changed the CMakeLists.txt to be:
```
include_directories(/usr/local/include/s2)

add_executable(myexe ${SOURCES})

target_link_libraries(myexe s2)
```
cmake .. worked, but when I run `make`:
![image](https://github.com/google/s2geometry/assets/137837175/f997010f-4c1a-4248-a710-c089d8d132d7)
Why can't s2geometry find absl?

Any idea on how to resolve this issue?
Thanks,

**Comment by smcallis** [comment]
I'll defer to @jmr since I don't poke at the CMake files much.  I'm not sure that we support FindPackage automatically.

**Comment by jmr** [comment]
What's the goal here? Are you trying to just get something working for yourself, or do you want do distribute a `CMakeLists.txt` for others to use?

> Why can't s2geometry find absl?

The error is from `cloud_mapper` not finding `absl`.  Did you also `make install` absl, or also add it to `include_directories`?

**Comment by GoroYeh-HRI** [comment]
I actually resolved this by writing the CMakeLists.txt as this:
![image](https://github.com/google/s2geometry/assets/137837175/f3ab6415-4920-4211-a46c-e53a298b49b9)

Also, I installed everything under `/usr/local/include` and it's able to find.
