### ISSUE TITLE
Can there be a new release cut?

### ISSUE THREAD

**Issue by jherico** [google/s2geometry#341]
I'm trying to get the vcpkg version of s2geometry updated so that it will build on windows, but the vcpkg maintainers don't want to accept an essentially random commit as a new build when this project already has a version history in vcpkg using tagged releases.

It seems like the google3 merge 9 months ago or anything subsequent to that would make a good spot for a version bump and a new build.  

Thanks.

**Comment by jmr** [comment]
I'm working on integrating the latest Google changes, but tagging what we have sounds reasonable.

**Comment by jmr** [comment]
I merged #339. I'll let you update on your side and test it. Let me know if it's good to tag HEAD.

**Comment by jherico** [comment]
my branch of vcpkg now builds s2 successfully without any patches required, targeting the commit `5c2190ab374dcfa7467bd4894e4db6038e60a131`.  As soon as you tag it I can change the ref to the tag from the commit ID and update the vcpkg PR.  Thanks.

**Comment by jmr** [comment]
https://github.com/google/s2geometry/releases/tag/v0.11.0
