### ISSUE TITLE
error for closest cell finding on brute force and optimal

### ISSUE THREAD

**Issue by simonzhangsm** [google/s2geometry#36]
FindClosestCellsBruteForce()
FindClosestCellsOptimized() 
will conduct different results

issue errors on s2closest_cell_query_test at TestFindClosestCells(...)

**Comment by jmr** [comment]
Is `s2closest_cell_query_test` failing for you? If so, could you paste all the test output here? The test passes for me.

**Comment by jmr** [comment]
What compiler and version are you using? I actually haven't tested on OS X in a while, so will see if I get the same thing there.

**Comment by simonzhangsm** [comment]
clang 4.2.1 with Apple LLVM version 9.1.0 (clang-902.0.39.2)

**Comment by simonzhangsm** [comment]
I have review the code in s2closest_cell_query.cc here: 
  vector<TestingResult> expected, actual;
  query->mutable_options()->set_use_brute_force(true);
  GetClosestCells(target, query, &expected);

  query->mutable_options()->set_use_brute_force(false);
  GetClosestCells(target, query, &actual);
if I set second query->mutable_options()->set_use_brute_force(true);, passed the test.
But if I use the origin codes, can not passed the test.

**Comment by jmr** [comment]
Now s2cell_index_test and s2closest_cell_query_test are both broken.

**Comment by jmr** [comment]
https://travis-ci.org/google/s2geometry/jobs/389345910

Failures are both:
`F0607 17:14:41.970665 2504209344 s2cell_index.h:479] Check failed: it_ != decltype(it_)() Call Begin() or Seek() first.`

I vaguely recall that you can't do anything with a default constructed iterator except assign to it.
