### ISSUE TITLE
Error in function InitToDifference

### ISSUE THREAD

**Issue by keyliaran** [google/s2geometry#39]
I have two polygons:
1) First (A) is a circle of radius R
2) Second (B)  is a circle of radius less than R (for example R/2)
Both circles has same center. Now im trying to InitToDifference C = A - B, so the right answer, i guess, is polygon that consist of A and reverse B, but the result is {A, B}.   
There is code without generation of A and B. Is it a bag or am i wrong?
  
   S2Polygon* union_res = new S2Polygon;
   std::cout << "First:\n";
   for(int i = 0; i < a->num_loops(); i++) {
        std::cout << a->loop(i)->GetArea() << "\n";
   }

    std::cout << "Second:\n";
    for(int i = 0; i < b->num_loops(); i++) {
        std::cout << b->loop(i)->GetArea() << "\n";
    }
    union_res->InitToDifference(a, b);
    std::cout << "Out:\n";
    for(int i = 0; i < union_res->num_loops(); i++) {
        std::cout << union_res->loop(i)->GetArea() << "\n";
    }

Output:
First:
0.00829343
Second:
0.0022473
Out:
0.00829343
0.0022473

**Comment by jmr** [comment]
It's hard to say without the code that generates `a` and `b`.

I'm assuming that `union_res->loop(2)->depth() == 1`, so this is a hole in the outer loop.  See the comments on [`S2Loop::depth`](https://github.com/google/s2geometry/blob/master/src/s2/s2loop.h#L208) and search for hole in both [`s2polygon.h`](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h) and [`s2loop.h`](https://github.com/google/s2geometry/blob/master/src/s2/s2loop.h).

Try testing [`S2Polygon::Contains(point)`](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L640) for both the center and a point in A \ B.

Also, the [`ToString` functions in `s2text_format.h`](https://github.com/google/s2geometry/blob/master/src/s2/s2text_format.h#L274) will let you have more informative debug output.

**Comment by keyliaran** [comment]
@jmr Yea, i see. I thought that polygon contains the number of loops and orientation of each loop is defined only by points order. Thx for the answer.

**Comment by ericveach** [comment]
Note that S2Loop::oriented_vertex() will return vertices in the order you
were expecting (i.e., holes and shells with opposite orientations).

Also, S2 supports a different polygon representation (S2LaxPolygonShape)
where the vertices are actually ordered this way.
