### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by zickau** [google/s2geometry#4]
Hi

Does the Python API support all native methods?

I would need set_min_level, set_max_level, and set_max_cells in S2RegionCoverer.

Or is it possible to access native methods from within python?

Kind regards

**Comment by akhenakh** [comment]
look at https://github.com/google/s2geometry/issues/2

**Comment by jmr** [comment]
No, it doesn't support all native methods, only the ones that are [`@unignored` in `s2_common.i`](https://github.com/google/s2geometry/blob/c47c9e448ffea16ef8569823bc12bb85fb9a9b35/src/python/s2_common.i#L188).

`set_min_level`, etc are being worked on right now, as mentioned in #2.

If there are any you need, list them here, or send a PR.
