### ISSUE TITLE
is there a stable release version?

### ISSUE THREAD

**Issue by acelyc111** [google/s2geometry#40]
I want to use s2geometry as a thirdparty library in my project, and don't want to modify it frequently, I find that the zip (https://github.com/google/s2geometry/archive/master.zip) is always refer to the latest master branch, so i want know is there any stable release version?
thanks

**Comment by ericveach** [comment]
No, currently there aren't any release versions.  We do try to ensure that
releases are stable though.  Generally changes have already gone through
quite a bit of testing before they are applied to the master.
