### ISSUE TITLE
CellUnion --> GeoJSON

### ISSUE THREAD

**Issue by zickau** [google/s2geometry#41]
Hi

What would be the easiest way to get from a S2CellUnion to MultiPolygons which can be used in GeoJSON or QGIS etc. to get a visual representation of the given S2CellUnion and overlay it with a city polygon for example?

Thx for any help

**Comment by ericveach** [comment]
Unfortunately GeoJSON support isn't part of the library.  The easiest
approach would be to just iterate through the cells in the union and output
a 4-vertex loop for each one.  You can get the vertices of a cell like this:

  S2Cell cell(cell_id);
  for (int i = 0; i < 4; ++i) {
    S2LatLng ll(cell.GetVertex(i));
    // Output [ll.lng(), ll.lat()]
  }

Note that S2Cell edges are spherical geodesics, not straight lines in
lat-lng space, so to visualize large cells correctly you need to draw the
edges as geodesics.  Not sure what tools you are using but you can do this
in Google Maps by setting options.geodesic = true.
