### ISSUE TITLE
DCHECK prevents execution of necessary code

### ISSUE THREAD

**Issue by oriubimo** [google/s2geometry#47]
https://github.com/google/s2geometry/blob/0239455c1e260d6d2c843649385b4fb9f5b28dba/src/s2/util/math/exactfloat/exactfloat.cc#L139

If DCHECK is disabled, the code inside it will not run, causing the function to give a wrong result.

**Comment by jmr** [comment]
It looks like that should be a CHECK, not DCHECK. Thanks.
