### ISSUE TITLE
Node.js Interface?

### ISSUE THREAD

**Issue by ghost** [google/s2geometry#48]
Would there be interest in creating a node.js wrapper with SWIG? I know it would be helpful to me as I mostly work in node.js and node-s2 from mapbox is getting out-of-date.

PS. I'd be willing to help create this. However, since I'm unfamiliar with SWIG and building node.js C++ interfaces more generally, it's probably not best that I lead.

**Comment by jmr** [comment]
It's probably best to open an issue asking node-s2 to update their geometry/ directory. @DennisOSRM @tmcw 

I see you already forked node-s2.

**Comment by tmcw** [comment]
Neither Dennis or I work at Mapbox anymore, so, yep - make a fork, fix it up, and promote ite.

**Comment by jmr** [comment]
I tried to build node-s2, and got this error, which apparently comes from the node version being too new:
```
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
```

The original reporter's account is now deleted, so I'll give up and close this for now.
