### ISSUE TITLE
absl conflict?

### ISSUE THREAD

**Issue by feng-y** [google/s2geometry#50]
third_party/absl/ will conflict [abseil-cpp](https://github.com/abseil/abseil-cpp)

**Comment by jmr** [comment]
Is this an actual or theoretical problem for you?

You could try `s/absl::/xabsl::/g` in the s2 code, and similarly (also `namespace absl {`, ...) in third_party/absl.

If you already have absl in your project, you could also try deleting third_party/absl and updating the includes in s2. I was using some parts of absl that hadn't yet been released, but maybe they've been released by now.

It's on my to-do list to [depend on absl correctly, according to their instructions](https://github.com/abseil/abseil-cpp/blob/master/CMake/README.md). I'd gladly merge a PR that does that.

There will still be some work to be done, in case you depend on multiple projects that all depend on absl.

**Comment by jmr** [comment]
I just committed 2c02e21040e0b82aa5719e96033d02b8ce7c0eff, which removes absl/base/integral_types.h. Now it wouldn't be too hard to add absl to your project (probably already done if you're complaining about conflicts), `rm -rf src/s2/third_party/absl`, and update the includes to point wherever you have absl.

You could also just make src/s2/third_party/absl/foo/bar.h include the real absl/foo/bar.h.

I'm still planning on making absl a git submodule eventually.

**Comment by jmr** [comment]
Update: it's still not quite that easy because the included `absl/base/port.h` has `using std::string`, but the released one doesn't.

**Comment by bhandras** [comment]
Here's some help to remove dependency from the source:

grep -Rl 's2/third_party/absl' | grep -v third_party/absl | less | xargs sed -i 's/s2\/third_party\/absl/absl/g'

vi -u NONE s2/base/port.h
#include <string>
using std::string;

vi -u NONE s2/s2latlng.h
#include "s2/base/port.h"

grep -Rl 'subtle::' | grep -v s2/third_party/absl | xargs sed -i 's/subtle::/absl::container_internal::/g'

vi -u NONE s2/strings/ostringstream.h
#include "s2/base/port.h"

Now one can just add absl to the CMakelist and it should build.

**Comment by feng-y** [comment]
Thanks @jmr ! `s/absl::/xabsl::/g`  works

**Comment by SpaceIm** [comment]
Any chance to have external abseil implemented? In the current state, `s2geometry` is not "package manager friendly" (embeded dependencies are evil, even more when they are public :s).
I tried to package `s2geometry` for conan but I gave up trying to make it work with latest version of abseil.

**Comment by jmr** [comment]
See #168
