### ISSUE TITLE
gcc undefined reference to ‘S2Testing::RandomPoint()’

### ISSUE THREAD

**Issue by wyfSunflower** [google/s2geometry#52]
After compile and install s2, In  the s2geometry/doc/examples/ directory. I run the following command
g++ term_index.cc -std=c++17 -I/usr/local/lib/ -ls2
it throw out  link error:
/tmp/ccxc1b2Q.o：in ‘main’：
term_index.cc:(.text+0x5a)：undefined reference to ‘S2Testing::RandomPoint()’
term_index.cc:(.text+0x2b5)：undefined reference to ‘S2Testing::RandomPoint()’
collect2: error: ld returned 1 exit status
Actually, I have included the s2testing.h yet.
#include "s2/s2testing.h"

**Comment by jmr** [comment]
The examples should be built when you run `make` from your `build` dir if you're following the instructions from [README.me](https://github.com/google/s2geometry/blob/master/README.md#building).

You could try adding `-ls2testing` to your command line if you want to build it yourself for some reason.

**Comment by wyfSunflower** [comment]
In the build folder, I have make project use the following command:
cmake -DGTEST_ROOT=/usr/src/gtest ..
make -j4
make test  -j4
sudo make install
~/s2geometry/doc/examples$ g++ -std=c++17 point_index.cc -ls2 -ls2testing
/usr/bin/ld: can not found -ls2testing
collect2: error: ld returned 1 exit status

**Comment by jmr** [comment]
If you follow the [README.md instructions](https://github.com/google/s2geometry/blob/master/README.md#building), it will be in `build/examples/term_index`.

The reason `-ls2testing` wasn't working for you was I forgot to install it. Should be fixed in 20c8f339cc9a55fdca1c0e8ab519da399752e70b.

**Comment by wyfSunflower** [comment]
Thanks! It now works.
