### ISSUE TITLE
Cover specified polyline or polygon with specified level cell

### ISSUE THREAD

**Issue by wyfSunflower** [google/s2geometry#55]
How to cover specified polyline or polygon with specified level cell?Thanks!

**Comment by jmr** [comment]
[Like I said in #51](https://github.com/google/s2geometry/issues/51#issuecomment-438387816), use [`S2RegionCoverer`](https://github.com/google/s2geometry/blob/master/src/s2/s2region_coverer.h) with [`set_fixed_level`](https://github.com/google/s2geometry/blob/dfefe0cd330f22463c0eca4338da69762cae7b49/src/s2/s2region_coverer.h#L133) as an `Option`. 

If the region is large, your fixed level covering will be large, so consider not using a fixed level. Also look at [`S2RegionTermIndexer`](https://github.com/google/s2geometry/blob/master/src/s2/s2region_term_indexer.h) and the [`term_index.cc` example](https://github.com/google/s2geometry/blob/master/doc/examples/term_index.cc).

What's the higher level problem you're trying to solve?

**Comment by wyfSunflower** [comment]
How to parallel execute S2RegionCoverer and S2RegionTermIndex on multi core platform?@jmr

**Comment by wyfSunflower** [comment]
I want to create a S2Polygone object, according to 
S2Polygon(std::vector<std::unique_ptr<S2Loop> > loops,
                     S2Debug override = S2Debug::ALLOW);
I need to convert  std::vector<S2Point> to std::vector<std::unique_ptr<S2Loop> >
I write in this way:
unique_ptr<S2Loop> *loops = new unique_ptr<S2Loop(vertices, S2Debug::DISABLE)>;
temporary of non-literal type ‘S2Loop’ in a constant expression
‘S2Loop’ is not literal because:
 class S2Loop final : public S2Region {
type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Dp> class std::unique_ptr’

**Comment by jmr** [comment]
> How to parallel execute S2RegionCoverer and S2RegionTermIndex on multi core platform?

If you mean how to get, say, `S2RegionTermIndexer::GetRegionTerms` to distribute its work over multiple threads, you don't. All these classes are single-threaded.

What you would generally do is parallelize at a higher level, perhaps running each shape you're indexing in its own thread.

**Comment by wyfSunflower** [comment]
std::vector<S2Point> vertices;
for(...){
   vertices.push_back(S2Point);
}
unique_ptr<S2Loop> *loops = new unique_ptr<S2Loop(vertices, S2Debug::DISABLE)>;
S2Polygon* polygon = new S2Polygon(loops, S2Debug::DISABLE);

**Comment by wyfSunflower** [comment]
std::vector<S2Point> vertices;
for(...){
   vertices.push_back(S2Point);
}
unique_ptr loops = new unique_ptr<S2Loop(vertices, S2Debug::DISABLE)>;
S2Polygon polygon = new S2Polygon(loops, S2Debug::DISABLE);

**Comment by wyfSunflower** [comment]
std::vector<S2Point> vertices;
for(...){
   vertices.push_back(S2Point);
}
unique_ptr loops = new unique_ptr<S2Loop(vertices, S2Debug::DISABLE)>;
S2Polygon polygon = new S2Polygon(loops, S2Debug::DISABLE);

**Comment by wyfSunflower** [comment]
I don't know how to create a S2Polygone object, could you please give me a demo about how to create S2Polygone? according to S2Polygon.h and S2Loop.h, first I need to use my std::vector<S2Point> vertices to construct a S2Loop object, then use this S2Loop object to construct a S2Polygone object, but S2Polygone can only accept S2Loop with std::unique_ptr type, I don't know  how to convert S2Loop to unique_ptr<S2Loop> or construct unique_ptr<S2Loop> object directly. Thanks

**Comment by wyfSunflower** [comment]
for a region cover function: first construct a S2RegionCover::Options by specified level and cell count, then use this object to construct a S2RegionCover object, this is simple. But how to construct a S2Region according to specified demand is difficult, since S2Region is a virtual base class, user can only construct its derived class, such as S2Loop, S2Polygone, S2Polyline, but S2Polygone is really difficult to construct, S2Loop is much more simple than S2Polygone, but it still need to check polygone orientation, if orientation is in constrast, the result is what I don't need. Could you give me a simple method to check polygone orientation?Thanks

**Comment by jmr** [comment]
> std::vector vertices;

It looks like you're having some C++ syntax issues. This would need to be `std::vector<S2Point> vertices;` This bug isn't the place for a C++ tutorial, though.

> I don't know how to create a S2Polygone object, could you please give me a demo about how to create S2Polygone?

Look at `s2polygon_test.cc`, there are many examples there. The [`LoopPointers`](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon_test.cc#L887) test case looks closest to what you want to do.

> S2Loop is much more simple than S2Polygone, but it still need to check polygone orientation, if orientation is in constrast, the result is what I don't need. Could you give me a simple method to check polygone orientation?

I'm not sure how you're having problems with loop orientation if your code doesn't compile, but maybe you're just planning ahead.  Look at the comments in [`s2polygon.h`](https://cs.corp.google.com/piper///depot/google3/util/geometry/s2polygon.h?q=s2loop&dr=C&l=53). [`S2Loop::Normalize`](https://github.com/google/s2geometry/blob/master/src/s2/s2loop.h#L230) will invert loops to cover at most half of the sphere. There are also `Invert` and `IsNormalized` functions. Just normalize all of your loops.

**Comment by wyfSunflower** [comment]
`int main(int argc, char** argv) {
    if(argc <= 2){
        std::cout << "please input a cell length in km: max cell num:\n";
        return -1;
    }
    
    double length_km = std::stod(argv[1]);
    int level =S2::kAvgEdge.GetClosestLevel(S2Earth::KmToRadians(length_km));
    S2RegionCoverer::Options options;
    options.set_fixed_level(level);
    options.set_max_cells(std::stoi(argv[2]));
    S2RegionCoverer coverer(options);
    
    std::vector<S2Point> vertices;
    CSVReader reader("/home/gml/PycharmProjects/split_5");//should be absolute path
    std::vector<std::vector<std::string> >dataList = reader.getData();
    
//    vector<S2LatLng> check_orientation;
//    for (int i=0; i < dataList.size(); i++)
//        check_orientation.push_back(S2LatLng::FromDegrees(stod(dataList[i][1]), stod(dataList[i][0])));
//    
//    if(get_polygone_orientation_according_to_vertex_order(check_orientation) == 1){
//    
//    }else if(get_polygone_orientation_according_to_vertex_order(check_orientation) == 2){
//    
//    }else if(get_polygone_orientation_according_to_vertex_order(check_orientation) == 0){
//        S2Polyline *line = new S2Polyline(check_orientation, S2Debug::DISABLE);
////        timespec read;
////        clock_gettime(CLOCK_REALTIME, &read);
////        cout<<"read data from file time:" << read.tv_nsec - start.tv_nsec << endl;
//        S2CellUnion covering = coverer.GetCovering(*line);
//    }else{
//        cout << "please input at least 3 vertices to construct a valid polygone!\n";
//        return -1;
//    }
    
    
    for(int i = dataList.size()-1; i>=0; i--){
        double lng = stod(dataList[i][0]), lat = stod(dataList[i][1]);
        vertices.push_back(S2LatLng::FromDegrees(lat, lng).ToPoint());
    }   
    
    dataList.clear();
    S2Loop* loops = new S2Loop(vertices, S2Debug::DISABLE);
//    unique_ptr<S2Loop> *lp = S2Loop(*loops);
//    S2Polygon* polygon = new S2Polygon(absl::make_unique<*loops->Normalize()>, S2Debug::DISABLE);
    S2CellUnion covering = coverer.GetCovering(*loops->Normalize()); //->Normalize()
    for(auto item : covering.cell_ids())
        std::cout << item.ToLatLng().Normalized().lng().degrees() <<"," << item.ToLatLng().Normalized().lat().degrees()<<"\n";
    vertices.shrink_to_fit();
    delete loops;
    return 0;
}
`
error: void value not ignored as it ought to be
     S2CellUnion covering = coverer.GetCovering(*loops->Normalize()); //->Normalize()

**Comment by wyfSunflower** [comment]
`int main(int argc, char** argv) {
    if(argc <= 2){
        std::cout << "please input a cell length in km: max cell num:\n";
        return -1;
    }
    
    double length_km = std::stod(argv[1]);
    int level =S2::kAvgEdge.GetClosestLevel(S2Earth::KmToRadians(length_km));
    S2RegionCoverer::Options options;
    options.set_fixed_level(level);
    options.set_max_cells(std::stoi(argv[2]));
    S2RegionCoverer coverer(options);
    
    std::vector<S2Point> vertices;
    CSVReader reader("/home/jmr/PycharmProjects/split_5");//read vertices data from file
    std::vector<std::vector<std::string> >dataList = reader.getData();
   // I don't know when need to invert vertices order of push_back into vector
    for(int i = dataList.size()-1; i>=0; i--){
        double lng = stod(dataList[i][0]), lat = stod(dataList[i][1]);
        vertices.push_back(S2LatLng::FromDegrees(lat, lng).ToPoint());
    }   
    
    dataList.clear();
    S2Loop* loops = new S2Loop(vertices, S2Debug::DISABLE);
    S2CellUnion covering = coverer.GetCovering(*loops->Normalize()); //can't compile
    for(auto item : covering.cell_ids())
        std::cout << item.ToLatLng().Normalized().lng().degrees() <<"," << item.ToLatLng().Normalized().lat().degrees()<<"\n";
    vertices.shrink_to_fit();
    delete loops;
    return 0;
}
`
error: void value not ignored as it ought to be
S2CellUnion covering = coverer.GetCovering(*loops->Normalize()); //can't compile

**Comment by jmr** [comment]
> `S2CellUnion covering = coverer.GetCovering(*loops->Normalize()); //can't compile`

```
loops->Normalize();
S2CellUnion covering = coverer.GetCovering(*loops);
```

If you normalize it, the direction you put it in the vector doesn't matter. Depending on where your data is coming from and what conventions it obeys, you might not need to reverse/`Normalize` at all, if you put them in an order so that the interior is to the left.
