### ISSUE TITLE
Bug in void S2Loop::InitBound() ?

### ISSUE THREAD

**Issue by mkrivos** [google/s2geometry#57]
I have polygon CW POLYGON ((-99 3, 92 3, 92 29, -99 29))
which return FULL Bound [-180:180,-90:90]. 
Is this correct ?

**Comment by ericveach** [comment]
The interior of a loop in S2 is always the region on its left.  In other words, they should be CCW around the region they contain.  This is a CW loop, so it contains the entire sphere *except* for the region you probably intended to define.  The bound is correct.

Also be aware that S2 edges are spherical geodesics, so even if you invert this loop the bound will have a greater latitude span than you are probably expecting.  You can use S2EdgeTessellator if you want to approximate a straight edge in lat/lng space (plate carree projection) with spherical geodesics.

**Comment by mkrivos** [comment]
Thank you very much.
