### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by DennisOSRM** [google/s2geometry#59]
Hey, having read #40, I'd like to push again for a tagged release. Reason for asking is that package managers, e.g. [Homebrew](https://github.com/Homebrew/homebrew-core), won't accept a package for S2 unless there is a tagged version. It would be very much appreciated.

**Comment by DennisOSRM** [comment]
Friendly ping

**Comment by jmr** [comment]
https://github.com/google/s2geometry/releases/tag/v0.9.0-2019.02.11.00

**Comment by DennisOSRM** [comment]
Thanks so much!

**Comment by fxcoudert** [comment]
This is marked as “pre-release”, is it voluntary?

**Comment by jmr** [comment]
Yes. We're not guaranteeing API stability yet.

**Comment by sgindin** [comment]
@jmr is lack of guarantee for the API stability the only thing preventing you from calling this 1.0.0?
And if it is not, is there a roadmap or desire to get there in the future?
IMO API stability alone shouldn't prevent you from cutting a release. For example, I'm pretty sure that for my project the API is stable enough.
@fxcoudert what is the real concern here?

**Comment by jmr** [comment]
I just wanted to unblock @DennisOSRM while imposing the minimum additional requirements. For release versions, the major number would have to be bumped for changes that aren't backwards compatible.

I think I want to remove the internal copy of abseil-cpp and fix some bugs before releasing a 1.0. Before this issue, we weren't planning on tagging releases at all.

**Comment by sgindin** [comment]
@jmr I see. Unfortunately Homebrew maintainers are not happy with the 'fake' release. Let me know if I can help with making 1.0.0 happen.

**Comment by jmr** [comment]
The bug said tag a release, not tag a release >= 1.0.0. What are the homebrew requirements, exactly?

**Comment by sgindin** [comment]
This is being discussed here https://github.com/Homebrew/homebrew-core/pull/37122
The rules are here https://docs.brew.sh/Acceptable-Formulae
The particular comment from the maintainer:
```
This is marked as as “pre-release”, which is not suitable for Homebrew core
```

**Comment by jmr** [comment]
Will 0.y.z work? Homebrew doesn't say what they think "stable" means.  Do they assume everything follows SemVer rules?f

It seems a bit strange to have detailed rules that provide no actual guarantees and ultimately depend on other people doing the right thing, but I guess it works well enough for them in practice.

**Comment by fxcoudert** [comment]
> It seems a bit strange to have detailed rules that provide no actual guarantees and ultimately depend on other people doing the right thing, but I guess it works well enough for them in practice.

Actually, it does :)

We ship 4725 packages, so we have to find rules that are general enough to keep us on the verge of sanity.

- We refuse to ship things that don't follow a versioning system, but we let upstream decide what they consider stable.
- We're okay with 0.x.y releases, because we do know that some usable (and useful) software can take decades to reach a 1.0.0 release, depending on how hard the developers are on themselves.
- We don't ship anything that upstream themselves consider “unstable”, “development”, “alpha” or “beta” releases.

In your case, what worried me was the “pre-release” tag on the github release. We understand that API might change in the future, but what I am wondering is whether you're just tagging this one release to satisfy a user, or if you will be releasing other releases in the not-so-far future.

**Comment by jmr** [comment]
There will be continued releases. 

I'm a bit concerned by the potential for conflicts with other versions of abseil-cpp, which currently doesn't want to be installed, or provide any install functionality (but they have promised it for the future).

**Comment by jmr** [comment]
@DennisOSRM How urgent is this for you? I could do a 0.9.0 release anytime, but there are always a few more changes I could do first...

**Comment by jmr** [comment]
@DennisOSRM Can you test https://github.com/google/s2geometry/releases/tag/v0.9.0-2019.03.01.00 ?

If that works for you I'll release v0.9.0.

**Comment by sgindin** [comment]
@jmr thanks! I'll integrate and test this branch ASAP and let you know.

**Comment by sgindin** [comment]
@jmr I've encountered an issue trying to build agains this version.
https://github.com/google/s2geometry/blame/v0.9.0-2019.03.01.00/src/s2/util/bits/bits.h#L56
This exposes gtest in the public API.

**Comment by jmr** [comment]
@sgindin Good point. Try https://github.com/google/s2geometry/releases/tag/v0.9.0-2019.03.04.00 .

**Comment by sgindin** [comment]
@jmr, thanks for the quick fix! I confirm that I could successfully build and test my project against v0.9.0-2019.03.04.00.

**Comment by jmr** [comment]
https://github.com/google/s2geometry/releases/tag/v0.9.0
