### ISSUE TITLE
Python bindings installation path is incorrect

### ISSUE THREAD

**Issue by akhenakh** [google/s2geometry#6]
The current cmake configuration does not search for the correct python site-packages directory and install the bindings in PREFIX/share/python, so it can't be loaded by the interpreter as is.

One solution would be to look for site-packages directory via `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`

The right way is probably to use python itself to build & install the bindings.

**Comment by jmr** [comment]
I've seen some pretty hairy CMake files to get this right. Could you point me at one I should follow?

**Comment by akhenakh** [comment]
OpenCV python bindings would be a good (not simple) example with cmake

If you hope for a larger audience on Python a packaging for Pypi would help  https://pypi.python.org/pypi/opencv-python with prebuilt binaries and all to ship the c++ library with Python but it's a long road ahead :)

**Comment by akhenakh** [comment]
One good reason would be an S2 plugins for QGIS

Something I've tried several times to work on but stopped because of packaging dependencies nightmare.
