### ISSUE TITLE
Use a slightly more modern CMake

### ISSUE THREAD

**Issue by bradhoov** [google/s2geometry#60]
I find the CMake file is a bit out of date and I would like to rewrite it to make it easier to use. In preparation for that, I would like to bump the version to 3.5. 
I think 3.5 is the lowest version it should be since Ubuntu 16.04 comes with 3.5. I don't think this should inconvenience people too much. Later versions of CMake are very easy to install and Ubuntu 18.04 comes with CMake 3.10.

**Comment by bradhoov** [comment]
#61

**Comment by jmr** [comment]
What are the features in 3.5 that you need that aren't in 3.1?

**Comment by bradhoov** [comment]
3.5 Allows for the use of Imported targets.

**Comment by jmr** [comment]
Sounds good, send a PR to just bump the version, and then I can merge #61 as a pure reformatting.
