### ISSUE TITLE
when i run the example code in clion ,it shows undefined reference to `S2Testing::RandomPoint()' ; Ubuntu 18.04

### ISSUE THREAD

**Issue by liang-zz** [google/s2geometry#64]
here my Cmakelists is:
`project(test)

set(CMAKE_CXX_STANDARD 17)

set(INC_DIR /usr/local/include/s2)
set(LINK_DIR /usr/local/lib)

include_directories(${INC_DIR})
link_directories(${LINK_DIR})
link_libraries(libs2.so)
 here is the error:
'add_executable(test main.cpp)`
`undefined reference to `S2Testing::RandomPoint()'
undefined reference to `S2Testing::RandomPoint()'`
I built this code yesterday. How can i do?Thanks!

**Comment by jmr** [comment]
> `link_libraries(libs2.so)`

Try `link_libraries(s2 s2testing)`.

The [`link_libraries` documentation](https://cmake.org/cmake/help/v3.5/command/link_libraries.html) says [`target_link_libraries`](https://cmake.org/cmake/help/v3.5/command/target_link_libraries.html#command:target_link_libraries) is preferred, so you might want to use that instead.  `target_link_libraries` has to come after `add_executable`.

Also, call your target `mytest` or something. There's a CMake warning that a target named`test` may result in undefined behavior.

Also see the [comment in `CMakeLists.txt`](https://github.com/google/s2geometry/blob/master/CMakeLists.txt#L210) about how projects can use s2 with `add_subdirectory`.

**Comment by liang-zz** [comment]
I am doing the above method.but i got a new error.
`/usr/bin/ld: /usr/local/lib/libs2.so: undefined reference to symbol '_ZN6google14FlagRegistererC1IiEEPKcS3_S3_PT_S5_'
//usr/lib/x86_64-linux-gnu/libgflags.so.2.2: error adding symbols: DSO missing from command line`

**Comment by jmr** [comment]
You also need to link against `gflags`. I think using `target_link_libraries` instead of `link_libraries` takes care of this for you, but am not that sure.

**Comment by liang-zz** [comment]
OK，Thank you very much!
