### ISSUE TITLE
Effective overlap query

### ISSUE THREAD

**Issue by benstadin** [google/s2geometry#66]
Does S2 support efficient overlap querying? I want to index polygons which can vary in size a lot (from room size to continent size), and efficiently check whether a point is within a region. 
A nearby search would find me the nearby vertices only, but not those covering the point which could be far away.

**Comment by jmr** [comment]
You say overlap query, but you seem to be describing a point containment query. Maybe I'm just not familiar with the terminology.

Does [`S2ContainsPointQuery`](https://github.com/google/s2geometry/blob/master/src/s2/s2contains_point_query.h) do what you want? Look at [`s2contains_point_query_test.cc`](https://github.com/google/s2geometry/blob/master/src/s2/s2contains_point_query_test.cc) for example uses.

Do all of your polygons fit in memory?

**Comment by benstadin** [comment]
Thanks for the link. I think the test case starting at line 107 is what I'm looking for. 

Yes, the polygons should all fit into memory. I want to create static set of regions from polygons of varying shape (will always be regular simple type polygons), and test if a moving location coordinate (position) is inside on of the indexed fences. Indexed regions may also overlap each other sometimes.

What is the Big O for the query round about?

By overlap I mean an intersection test, which also includes the border of the indexed polygon and not only tests if it's contained within. It is important for me that the intersection test between the original defined polygon region and position coordinate is exact.

**Comment by jmr** [comment]
> What is the Big O for the query round about?

You can think of it as O(log(num_shapes)).

> It is important for me that the intersection test between the original defined polygon region and position coordinate is exact.

I'm not sure of the exact guarantees, but you don't have the input geometry exactly, and the conversion from lat/lng to `S2Point` also isn't exact, so maybe rethink this.
