### ISSUE TITLE
Is googletest optional or not?

### ISSUE THREAD

**Issue by jason-watkins** [google/s2geometry#67]
The Readme says

> Requirements for End Users
> 
>   *  ...
>   *  googletest testing framework (to build tests and example programs, optional)

Despite this, the `s2testing` library is included in the build unconditionally, which in turn includes the file `s2shapeutil_testing.cc`, which includes `gtest/gtest.h`.

So it seems to me that googletest is required in practice. I'm not sure if the readme just needs to be updated to say that googletest is required or if the `s2testing` library should be included in the conditional test block.

**Comment by jmr** [comment]
It's a bug.

**Comment by hpolloni** [comment]
PR: https://github.com/google/s2geometry/pull/78

**Comment by figroc** [comment]
@jmr #78 has been updated with CLA signed. Would you kindly give a review?
