### ISSUE TITLE
Cannot find S2MultiBooleanOperation class

### ISSUE THREAD

**Issue by houes** [google/s2geometry#69]
Hello, friends,

I found in the s2boolean_operation.h file, the author mentioned S2MultiBooleanOperation which can do boolean operations on multiple objects. However I cannot find any where in the code that has this S2MultiBooleanOperation class. Any ideas why?

I need to union a set of S2Polygons and I find using S2BooleanOperation to do this union one by one to be very slow.

If anyone could give me some advise, that would be great! Thank you.

Best,

**Comment by jmr** [comment]
It hasn't been implemented yet. Sorry.

**Comment by houes** [comment]
I see. Thank you. Will be happy to see it coming.
