### ISSUE TITLE
Export include directories

### ISSUE THREAD

**Issue by andreaskipf** [google/s2geometry#7]
Adding the following line to CMakeLists.txt
```
target_include_directories(s2 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/src)
```

would allow to seamlessly include S2 in a different CMake project like this:
```
list(APPEND CMAKE_MODULE_PATH "<path_to_s2geometry_folder>/third_party/cmake")
add_subdirectory(<path_to_s2geometry_folder> s2geometry)
target_link_libraries(<target_name> s2)
```

**Comment by jmr** [comment]
[Done](https://github.com/google/s2geometry/blob/cdf1a05acf462ad60e1110a354c86e0b606c8931/CMakeLists.txt#L142). Reopen this if it doesn't work for you.
