### ISSUE TITLE
Why there are overlaps among adjacent google s2 cells.

### ISSUE THREAD

**Issue by Simonhong111** [google/s2geometry#70]
Thank you for your contribution.I use S2RegionCoverer class to get specific region covering cells,and i get overlaps among adjacent google s2 cells.Here is my code.
`    S2RegionCoverer::Options options;
    options.set_min_level(level);
    options.set_max_level(level);
    S2RegionCoverer s2RegionCoverer(options);

//    s2RegionCoverer.GetInteriorCovering(region,interior);
    s2RegionCoverer->GetCovering(region,interior);`
I try three type of `region,`S2LatLngRect,S2Loop,S2Polygon`,and the result is same.Could you give me some Suggest?

**Comment by jmr** [comment]
You get overlaps between what and what?

Can you make a fully contained test case that makes it clear what isn't behaving the way you expect?

**Comment by Simonhong111** [comment]
Thanks for help.The details of my issue as follows:
I want to get covering of a rectangle region with specific cell level,And I have got four vertex of it.Then I calculate region's cover cell number,and I get an unexpected number.
Here is my code.[code.txt](https://github.com/google/s2geometry/files/3168548/code.txt)
Here is the result.[2019-05-11_104822](https://user-images.githubusercontent.com/16298318/57564217-ec895a00-73da-11e9-8ed6-54fb933170a2.jpg)
As the result show,I have got overlaps between upper and lower cells,what is wrong with my code?

**Comment by jmr** [comment]
It looks like the `S2Cell`s aren't overlapping, it's their `RectBound`s, which is expected.

Instead of
```
S2Cell *s2Cell = new S2Cell(id);
std::unique_ptr<S2Cell> cell(s2Cell);
S2LatLngRect s2LatLngRect = cell->GetRectBound();
S2LatLng lb = s2LatLngRect.GetVertex(0);
...
```

just call
```
S2Cell s2Cell(id);
S2LatLng lb = s2Cell.getVertex(0);
...
```

> the expect of the cell number is 60,but I get 400

Why are you expecting 60?  Also note that [`min_level` takes precedence over `max_cells`](https://github.com/google/s2geometry/blob/master/src/s2/s2region_coverer.h#L80).

**Comment by Simonhong111** [comment]
Thanks for respond.I have used Java S2 Library and level=12,the result is 61.As you seen,I use C++ Library to test,and the number should be Around 60.And I see almost test case in Internet,they cell is Parallelogram,but in my test case cell is rectangle.This problem has puzzled me for a long time.
![Screenshot from 2019-05-11 20-55-15](https://user-images.githubusercontent.com/16298318/57569973-5a5f7100-742f-11e9-9912-ea82f030b648.png)
As this picture show,these parallelograms are closely arranged but do not cover each other.In fact,I need effect like that case.

**Comment by jmr** [comment]
Did you try removing the `getRectBounds` call, and getting the vertices directly from the `S2Cell`? That's what's causing your problems.

I think the Java version must be using different options. Try removing the `set_min_level` and `set_max_level` and just `set_max_cells(60)` and see what happens. Or, set min and max levels to something reasonable but not the same.

**Comment by Simonhong111** [comment]
Thanks for helping.I have try the way you said,it works perfect.I am sorry that I didn’t understand what you mean at the beginning.my result is the external rectangle of the grid,because of `S2LatLngRect s2LatLngRect = cell->GetRectBound();`.Thank you for your contribution and answer.
