### ISSUE TITLE
S2Cells for a "negative/inverse" polygon?!

### ISSUE THREAD

**Issue by zickau** [google/s2geometry#76]
Hi *

I would need the functionality/method to get all S2Cells for a given (very precise) polygon, lets say a country, that returns all S2Cells outside the polygon, i.e., the 5 faces plus all other S2Cells of the polygon surrounding the given area in face 6.

Is that somehow possible to calculate?

Kind regards + thx for any reply
Sebastian

**Comment by jmr** [comment]
Call [`S2Polygon::Invert`](https://github.com/google/s2geometry/blob/master/src/s2/s2polygon.h#L485), then get a covering of that polygon.
