### ISSUE TITLE
Getting nearest neighbors with S2 geometry. 

### ISSUE THREAD

**Issue by winash12** [google/s2geometry#80]
I am looking for a S2 geometry version of this SE answer - [https://gis.stackexchange.com/questions/18330/using-geohash-for-proximity-searches/92331#92331]()

1) I want to use S2 cells to do approximate nearest neighbor searches

2) I have a bounding box on a 2D grid i.e. composed of latitudes and longitudes. For each latitude and longitude I want a S2 cell.These need to be "indexed" with a particular precision. That precision needs to be linked to a radius in kilometers or meters. 

3) Then I have a whole bunch of query coordinates completely unrelated to the above  coordinates. So I can convert this coordinate to a index as well and maybe get's neighbors as well. These can be indexed at a lower precision. 

4) Then use this index to return nearest neighbors from the original bounding box. Here  I am assuming some bit shifting will have to be done. 

I have a highly optimized SkipList which does fast inserts and range queries. So the range query would return coordinates from the bounding box given the lower and upper range values from (3). 

Is that possible with s2 geometry ?

**Comment by a1983** [comment]
Strange issue. It seems [S2ClosestPointQuery](http://s2geometry.io/devguide/cpp/quickstart) is what you want.

**Comment by winash12** [comment]
@a1983 Looks a good API to use. Certainly will do what I want.

Can you clarify on the precision part ? Should I index at the highest "level" which I believe is 30 for my bounding box coordinates ? 

I also need to know what  precision I should index my query coordinates.

**Comment by jmr** [comment]
What @a1983  said.

@winash12: you don't need to worry about "precision" or which level to index at. Just create an `S2PointIndex`, add your points, then use `S2ClosestPointQuery` to find the closest points. There's an example in [`point_index.cc`](https://github.com/google/s2geometry/blob/master/doc/examples/point_index.cc).

**Comment by 925781609** [comment]
> Strange issue. It seems [S2ClosestPointQuery](http://s2geometry.io/devguide/cpp/quickstart) is what you want.

Sorry, this is only available in C++. Does java has the same function or can achieve the same function？
