### ISSUE TITLE
MacOS Linker Problem

### ISSUE THREAD

**Issue by DinosL** [google/s2geometry#87]
Hello,

`make` command fails with the following error

`ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libs2.dylib] Error 1
make[1]: *** [CMakeFiles/s2.dir/all] Error 2
make: *** [all] Error 2
`

That is not the first time i encounter this error after upgrading and I suppose it is a Catalina error. I have already tried `xcode-select --install ` but it is not working.

Any suggestions?

Thank you in advance

**Comment by jmr** [comment]
I don't think I'll be upgrading to Catalina for a long time.  Can you install openssl / `libcrypto` with MacPorts or homebrew and use that one?

**Comment by DinosL** [comment]
I already had openssl installed so I run ``` brew upgrade openssl ```. This took some minutes because it upgraded all the dependencies to be compatible with Catalina. Now it works fine.

I have encountered so many problems with libraries and 32-bit apps and I can agree that you should not upgrade yet.

Have a nice day

**Comment by jmr** [comment]
We should at least update the code to explain the Catalina workaround.

**Comment by DinosL** [comment]
I am not sure I understand what you mean. I did not make any changes to the code. I just upgraded openssl using the above command and then re-installed s2 using your [build instructions](https://github.com/google/s2geometry#building). Now I can run the same code I was running on Linux on macOS.

**Comment by jmr** [comment]
If it works with brew upgrade, then it's ok. I thought there might be extra, special steps for Cataline.

**Comment by CloudNiner** [comment]
It appears that this issue might be back. Brew removed openssl 1.0 in brew 2.2.0, see https://github.com/kelaberetiv/TagUI/issues/635 which links to the brew changelog.

I attempt to run the following:
```
mdkir build
cd build
cmake -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl@1.1/1.1.1d/include/ ..
make s2
```
and get:
```
[100%] Linking CXX shared library libs2.dylib
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libs2.dylib] Error 1
make[2]: *** [CMakeFiles/s2.dir/all] Error 2
make[1]: *** [CMakeFiles/s2.dir/rule] Error 2
make: *** [s2] Error 2
```

on MacOS Catalina, brew 2.2.10, openssl@1.1: 1.1.1d. As above, xcode tools were already installed with `xcode-select --install`

**Comment by lpicanco** [comment]
It worked for me using these steps:

```
sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.dylib
sudo ln -s /usr/local/Cellar/openssl@1.1/1.1.1g/lib/libssl.1.1.dylib /usr/local/lib/libssl.dylib
cmake [normal arguments] -DOPENSSL_CRYPTO_LIBRARY="/usr/local/lib/libcrypto.dylib" -DOPENSSL_SSL_LIBRARY=/usr/local/lib/libssl.dylib
```
macOS Catalina
Homebrew 2.4.2
openssl@1.1/1.1.1g
