### ISSUE TITLE
Support for python Encode / Decode

### ISSUE THREAD

**Issue by ryanchapman** [google/s2geometry#9]
Hi,

I'm trying to encode and decode a polygon using as an example the C++ tests, and the Encoder() class doesn't seem to work the same, or maybe it isn't yet exposed in the SWIG files.

```Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywraps2 as s2
>>> london = s2.S2LatLng.FromDegrees(51.5001525, -0.1262355)
>>> src = s2.S2Polygon(s2.S2Cell(s2.S2CellId(london)))
>>> encoder = s2.Encoder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Encoder'
```

Is there a different way to accomplish this in python?

**Comment by jmr** [comment]
I'll need to add a coding.i file wrapping the Encoder/Decoder.

**Comment by jmr** [comment]
Until I get the coding.i file added, try adding this in the [`%extend S2Polygon` block in `s2_common.i`](https://github.com/google/s2geometry/blob/master/src/python/s2_common.i#L155).

```c++
  string Encode() const {
    Encoder encoder;
    $self->Encode(&encoder);
    return string(encoder.base(), encoder.length());
  }

  bool Decode(const string& encoded) {
    Decoder decoder(encoded.data(), encoded.size());
    return $self->Decode(&decoder);
  }
```

That should get you started, assuming there aren't too many types you need to encode/decode.

**Comment by ryanchapman** [comment]
Thanks! I was able to encode and decode polygons successfully.  I'll see if I can extend this to other types.

**Comment by jmr** [comment]
[I added Encoder/Decoder to the SWIG](https://github.com/google/s2geometry/blob/master/src/python/pywraps2_test.py#L246), so it should work for you without additional effort.

Having the string versions would be more convenient, though.
