### ISSUE TITLE
undefined reference to `S2LatLng::ToPoint() const'

### ISSUE THREAD

**Issue by DinosL** [google/s2geometry#90]
I am getting the following error when trying to compile and I cannot understand why. 
```
/usr/bin/ld: /tmp/ccOefUDg.o: in function `test()':
main.cpp:(.text+0x806f): undefined reference to `S2LatLng::ToPoint() const'
````
I compile using the command below on Ubuntu.

```
g++ -std=c++14  -ls2   main.cpp -o prog
```
I tried to compile using the -I and -L options of g++ to link the library but I get the same error.

Any ideas?

**Comment by jmr** [comment]
I didn't try to reproduce, but I think you need to do
```
g++ -std=c++14 main.cpp -ls2 -o prog
```
`-l` isn't a normal flag. It gets processed in order. So it links `s2` with nothing, forgets about it entirely, then compiles `main.cpp` and has unresolved symbols.

**Comment by DinosL** [comment]
That was the case for ubuntu indeed. It is weird because that does not happened with openmp.

However, that was not the case for macOS, where i get the following error.

```
 "S2Polygon::S2Polygon(std::unique_ptr<S2Loop, std::default_delete<S2Loop> >, S2Debug)", referenced from:
      checkIntersection() in cc7uPuym.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by jmr** [comment]
Is that the only error? Can you show your command line and code?

**Comment by DinosL** [comment]
Command Line : 

```
g++-9 -std=c++14 main.cpp -I/usr/local/opt/libomp/include -I/usr/local/Cellar/s2geometry/0.9.0_1/include -fopenmp -ls2 -L/usr/local/opt/libomp/lib -L/usr/local/Cellar/s2geometry/0.9.0_1/lib -o prog
Undefined symbols for architecture x86_64:
  "S2Loop::S2Loop(std::vector<Vector3<double>, std::allocator<Vector3<double> > > const&)", referenced from:
      std::_MakeUniq<S2Loop>::__single_object std::make_unique<S2Loop, std::vector<Vector3<double>, std::allocator<Vector3<double> > >&>(std::vector<Vector3<double>, std::allocator<Vector3<double> > >&) in ccZ9Ppni.o
  "S2Polygon::S2Polygon(std::unique_ptr<S2Loop, std::default_delete<S2Loop> >, S2Debug)", referenced from:
      checkIntersection(Record const&, Relation*, int, std::vector<int, std::allocator<int> >&, int) in ccZ9Ppni.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

Code : 

```
vector<S2Point> points1;

for(auto i = s.geometry->begin(); i != s.geometry->end()-1; i++)
{
    points1.push_back(S2LatLng::FromDegrees(i->x, i->y).ToPoint());
}
S2Polygon a(make_unique<S2Loop>(points1));
```

**Comment by DinosL** [comment]
Don't bother. I found it. I move the -fopenmp and -ls2 at the end and it works. I forgot to change my makefile that is why i posted the wrong g++ command above

**Comment by DinosL** [comment]
Any updates?

**Comment by jmr** [comment]
Here are a few things I would try:
* Use the compiler that `CMake` found. Was it `g++-9` or something else?
* Use `nm` to check if those symbols are in `libs2.dylib`. 
* It looks like some of the missing symbols are conditional on `#ifndef SWIG`. Did `SWIG` somehow get `#define`d?
* Do the examples work? Modify `doc/examples/CMakeLists.txt` to build your program.

**Comment by DinosL** [comment]
I had a clue that the compiler version was 'wrong' as I run some tests with g++ instead of g++-9 and it worked. But, I have to run with g++-9 because I cannot run -fopenmp with g++. That is a system-specific problem and I won't bother you with more details.

Following your suggestion to check the compiler version, I looked a little bit further. I managed to make it work with g++-9 and I want to write some notes in case anyone is interested or encounters the same problem in the future. I will try to keep it as detailed as possible.

I followed the build instructions but I changed the ```cmake``` command to : 
``` cmake -D CMAKE_CXX_COMPILER=/usr/local/Cellar/gcc/9.1.0/bin/g++-9 -DGTEST_ROOT=/...absolute path to.../googletest-release-1.8.0/googletest .. ```

Then, I got the following error when using ```make``` : ```__OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);```. I found information regarding this error [here](https://trac.macports.org/ticket/59113). Following the following comment I fixed it.

```
How to use Xcode 11 with MacPorts for now:

-Find an 10.14 SDK (like in your Xcode 10, for example).
-Put it somewhere, like /Library/Developer/SDKs/:
-Upgrade to Xcode 11, and symlink the MacOSX10.14.sdk back:
-sudo ln -s /Library/Developer/SDKs/MacOSX10.14.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk

```

If that does not work, one can try reinstalling gcc using ``` brew reinstall gcc```

The next error was ``` Error: Unable to find 'python.swg'``` and it happened at 100% of make. Solved using ```sudo port install swig-python```.

Now that the installation was finished, I was able to compile with no errors after adding ``` -I/usr/local/include/ ``` and ``` -L/usr/local/lib/ ``` to g++. The final command is ```g++ -std=c++14 -I/usr/local/include -L/usr/local/lib main.cpp -ls2 -o prog```

That 's all folks. If I remember anything else, I will edit this post.

Thank you for your help.
