### ISSUE TITLE
wrong python site path on ubuntu

### ISSUE THREAD

**Issue by figroc** [google/s2geometry#93]
I build `pywraps2` in ubuntu 18.04 docker. After running `make install`, the `pywraps2` can not be imported in python code. 
```bash
root@baf9f2a1dae5:/$ python3 -c 'import pywraps2' 
Traceback (most recent call last): 
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pywraps2'
```

In the `CMakeLists.txt` from `src/python`, `pywraps2` is installed into `${PYTHON_SITE}`. And that path is derived from command:
```cmake
execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c "if True:
                  from distutils import sysconfig as sc;
                  print(sc.get_python_lib(prefix='', plat_specific=True))"
                OUTPUT_VARIABLE PYTHON_SITE
                OUTPUT_STRIP_TRAILING_WHITESPACE)
```
The output from above command is: `lib/python3/dist-packages`. But if the `prefix` is not set to empty when invoking `sc.get_python_lib`, the output is `/usr/lib/python3/dist-packages`. And the default install prefix of cmake is `/usr/local`. So that the `pywraps2` will be installed into wrong path `/usr/local/lib/python3/dist-packages`.

**Comment by jmr** [comment]
Can you try with #128? The code you referenced will no longer exist with that PR. Perhaps the new way will work better.

**Comment by jmr** [comment]
#128 has been merged, you can try at HEAD.

**Comment by figroc** [comment]
I tried the HEAD today. Built and installed the lib in a bare `ubuntu:18.04` docker container. The python files get installed into the correct directory:
```bash
...
-- Installing: /usr/local/lib/libs2.so
-- Installing: /usr/local/lib/libs2testing.a
-- Installing: /usr/lib/python3/dist-packages/_pywraps2.so
-- Set runtime path of "/usr/lib/python3/dist-packages/_pywraps2.so" to ""
-- Installing: /usr/lib/python3/dist-packages/pywraps2.py
```

But it cannot be imported successfully:
```bash
root@ca6314814ed1:/work/build# python3 -c 'import pywraps2'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pywraps2.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libs2.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pywraps2.py", line 17, in <module>
    _pywraps2 = swig_import_helper()
  File "/usr/lib/python3/dist-packages/pywraps2.py", line 16, in swig_import_helper
    return importlib.import_module('_pywraps2')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libs2.so: cannot open shared object file: No such file or directory
```

I have to create the soft link to `libs2.so` in `/usr/lib`. Until then the `pywraps2` can be imported successfully.

**Comment by jmr** [comment]
> I have to create the soft link to `libs2.so` in `/usr/lib`. 

I don't think that's the right solution. You probably either want to put `/usr/local/bin` in `LD_LIBRARY_PATH` or add it to `/etc/ld.so.confi.d`.

https://unix.stackexchange.com/a/67783

**Comment by figroc** [comment]
> > I have to create the soft link to `libs2.so` in `/usr/lib`.
> 
> I don't think that's the right solution. You probably either want to put `/usr/local/bin` in `LD_LIBRARY_PATH` or add it to `/etc/ld.so.conf.d`.
> 
> https://unix.stackexchange.com/a/67783

Yes, you are right. But my point is that there would be no issue at all if I built a wheel and installed it.

**Comment by figroc** [comment]
At least. #128 fixes the python site path issue.

**Comment by jmr** [comment]
Ok, then I'll close this one.
